### ISSUE TITLE
troubles to run basic.js example

### ISSUE THREAD

**Issue by camous** [CacheControl/json-rules-engine#1]
I'm farirly new to node world but I'm facing troubles running the basic.js example. I'm sure I'm just looking in the wrong direction.

I've followed the script from travis (https://travis-ci.org/CacheControl/json-rules-engine) in order to copy-cat the setup of the json-rules-engine. I've successfully ran into unit test with success.

however, how I could run basic.js ? if I go in ./examples folder and run node basic.js. I'm getting following message 
![image](https://cloud.githubusercontent.com/assets/8566299/14424101/8ef64758-ffdf-11e5-8c63-652c5b9d3869.png)

any idea or direction to look for ?
many thanks.

**Comment by CacheControl** [comment]
@camous sorry about that, my fault entirely!  The example was the last thing I worked on for this project, but then I left on holiday and just got back.  I'll look into this tonight and get back to you.  Apologies again!

**Comment by CacheControl** [comment]
@camous I've fixed & updated the basic example - please let me know if you have any further issues, or questions about how to use.

also, since you're one of the early discoverers of this library, if you have any suggestions on ways the documentation could be more clear or feature requests, I'd love any feedback you can offer.

**Comment by camous** [comment]
@CacheControl I'm now able to run the example. that's cool.

Right now, I figured out that what I was trying to achieve was simpler than expected and might not requires a rules engine. However if my assumption is wrong in the future, I will give another try: I like the clear rules definitions and the event based actions.

However, and maybe nothing can be done here, the number of dependencies is high.
![image](https://cloud.githubusercontent.com/assets/8566299/14595984/935f5578-0543-11e6-82eb-0825aa4004de.png)

**Comment by CacheControl** [comment]
@camous cool, glad it worked for you!

re: the dependencies, when you install this as an npm package, it will be far smaller (640K in fact).  When you do a git checkout of the entire repo, it downloads all the dev-dependencies, which are substantial.
