### ISSUE TITLE
Is rule chaining supported?

### ISSUE THREAD

**Issue by alpendergrass** [CacheControl/json-rules-engine#10]
I have spent a few hours coming to understand your engine and I really like what I've seen so far. However, I do not understand if and how rule chaining works. That is, how do I trigger rules based on the results from other rules?

**Comment by alpendergrass** [comment]
OK, I think I'm starting to get it. Just read this at the bottom of the Almanac page: "When a rule evalutes truthy and its event is called, new facts may be defined by the event handler. Note that with this technique, the rule priority becomes important; if a rule is expected to define a fact value, it's important that rule be run prior to other rules that reference the fact." Lightbulb moment. So how about we turn this question into a request for an example illustrating chaining techniques?

Again, really like your work.

**Comment by CacheControl** [comment]
@alpendergrass Sorry for the late response, I've been on holiday.  Thanks for the kind words, I'm glad this library is providing some value.  I also agree that rule chaining is important enough to warrant a dedicated example!  I should be able to cook one up this weekend. 

I'll make this as an enhancement until we can get an example authored.  Thanks for the feedback!

**Comment by CacheControl** [comment]
@alpendergrass I've added an example as part of #13 .  Additionally, that PR formalizes rule chaining in the [documentation](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#rule-chaining).  Thanks again for bringing this to my attention.
