### ISSUE TITLE
Question: Engine lifecycle and arrays as fact

### ISSUE THREAD

**Issue by Ackos95** [CacheControl/json-rules-engine#100]
Hey guys, I have two questions, I've been reading through the docs, and couldn't actually find answers to two of my questions.

First one is about lifecycle of the engine, I'm not sure when I should re-use engine already created and when I should create new one. For example if I have 10 different rules defined, and changeable facts (each execution different ones) how should I handle that. 

Will facts override each other if inserted by same key (without removing)? I'm assuming that they will, but not sure tho. Also I'm a bit concerned about performance with bunch of rules, if I understood correctly all rules will be evaluated (when engine run), and I'm interested in only few per fact change (one execution), would those other ones slow the progress? Meaning should I add only rules which I'm interested in before running evaluation for some fact combination?

Also is there a way to just simply run engine in some kind of an infinite loop, attach to it's events and simply update facts in it, or on each fact change I need to run it again?

Second part of the question is about arrays, it is a bit related to #99, I'm trying to use engine as a filtering machine. For example

```js
const books = [
    { author: 'Author1', publishYear: 1999, title: 'Title 1' },
    { author: 'Author2', publishYear: 2005, title: 'Title 2' },
    { author: 'Author3', publishYear: 2011, title: 'Title 3' }
];

const filterRule = {
  conditions: {
    all: [
      {
        fact: 'book',
        operator: 'greaterThan'
        path: '.publishYear',
        value: 2004
      }
    ],
    event: {
      type: 'filter-event'
    }
  }
};

const engine = new require('json-rules-engine').Engine();

// this is how it "has" to be done now
Promise.all(books.map((book) =>
  engine.run({ book })
    .then((events) => events.length > 0)  // only one rule - only one type of event can be, if there is any rule is successfully evaluated
    .catch((err) => false)
)).then((values) => {
  // here I can get filtered books
  const filteredBooks = books.filter((_, index) => values[index]);
});
```

Is there a way to do this simpler, to avoid running one rule per array item?

**Comment by CacheControl** [comment]
> I'm not sure when I should re-use engine already created and when I should create new one.

Create a new engine when you need to run a new set of rules.  Re-use an existing engine when the facts have changed but the rules have not.

> Will facts override each other if inserted by same key (without removing)? 

Yes

> Should I add only rules which I'm interested in before running evaluation for some fact combination

Ideally, yes.  Though with that approach there may be a tradeoffs between code simplicity and performance.  I'd encourage you to run some basic benchmarks to see how many ms are actually being saved.

> Is there a way to do this simpler, to avoid running one rule per array item?

There are alternative options involving dynamic facts or custom operators, but unfortunately they're not simpler and I doubt you'd be happy with them.  This is a great use case for us to know about though, and adds supporting evidence for introducing json-path as a feature.

hope that helps!

**Comment by divyav17** [comment]
I am also facing similar functionality, Is there any suggested alternatives?
