### ISSUE TITLE
Event Driven Facts

### ISSUE THREAD

**Issue by tjmcclure0501** [CacheControl/json-rules-engine#107]
Not an issue - just a question.  I was wondering the best way to leverage this engine in an event driven architecture.  I want rules to run when certain events are fired and if the event satisfies the facts of the rule emits a rules engine event.  Any ideas on how to do this.  I could poll the data from a database where the events are stored but I would rather the engine be feed events directly.

**Comment by vantreeseba** [comment]
Can you add a listener to the events that would trigger an engine.run passing the events context/params as the facts into the engine.run method?

**Comment by tjmcclure0501** [comment]
Yes - that is what i thought - thanks for the clarification.
