### ISSUE TITLE
Persisting Rules With Variable Values

### ISSUE THREAD

**Issue by tjmcclure0501** [CacheControl/json-rules-engine#109]
I want to persist and later retrieve a rule from a database but I am not sure how to do this as the value for my rule is variable.  Here is my code:
 addRules(engine) {
    let message = {somevalue:'somevalue'};
    let rule = new Rule({
      // define the 'conditions' for when "hello world" should display
      conditions: {
        all: [{
          fact: 'instance',
          operator: 'evaluateTrigger',
          value: message
        }]
      },
      // define the 'event' that will fire when the condition evaluates truthy
      event: {
        type: 'alert',
        params: {
          data: 'makemodel'
        }
      }
    });
    this.logger.error('rule',rule.toJSON());
    engine.addRule(rule);
  }

The rule toJSON produces this:
rule{  
   "conditions":{  
      "priority":1,
      "all":[  
         {  
            "operator":"evaluateTrigger",
            "value":{  
               "somevalue":"somevalue"
            },
            "fact":"instance"
         }
      ]
   },
   "priority":1,
   "event":{  
      "type":"alert",
      "params":{  
         "data":"makemodel"
      }
   }
}

As you can see the variable was serialized out - when I read it from the database it will have the hardcoded values.

**Comment by tjmcclure0501** [comment]
I figured out a way around this.

**Comment by tjmcclure0501** [comment]
Figured it out

**Comment by kobvel** [comment]
@tjmcclure0501 how did you solve it?
