### ISSUE TITLE
Engine.run() return default value if conditions are not met

### ISSUE THREAD

**Issue by djemalmohamed** [CacheControl/json-rules-engine#110]
Hello,

I need to return a default result (default event.params.data) when conditions are not met for the given facts values.

Is this possible please?

ex: if we run this rule with a runtime fact {group: pilot}, the expected result is [false] and not an empty return data:

      rule: {
        conditions: {
          priority: 1,
          all: [
            {
              fact: 'group',
              operator: 'equal',
              value: 'admin',
            },
          ],
        },
        priority: 1,
        event: {
          type: 'admin',
          params: {
            data: true,
          },
        },
      },

**Comment by CacheControl** [comment]
One option here would be to have an _additional_ rule that inverts the logic, e.g.
```js
rule: {
    conditions: {
      priority: 1,
      all: [
        {
          fact: 'group',
          operator: 'notEqual', // only passes when the other rule fails
          value: 'admin',
        },
      ],
    },
    priority: 1,
    event: {
      type: 'admin',
      params: {
        data: null,  // default value
      },
    },
  },  
```

Alternatively, json-rules-engine provides a `failure` event, [documented here](https://github.com/CacheControl/json-rules-engine/blob/master/docs/rules.md#ruleonfailure-functionobject-event-almanac-almanac-ruleresult-ruleresult).  With that event, you can detect when this rule is failing and set a fact/variable to the default value.  This option is a bit hackier, but may be more viable than creating an inverse version of every rule.

Finally, if we were to turn this into a feature, it sounds like this is a request for a `failureEvent` property on the rule object, which would trigger whenever the conditions evaluate falsey.
