### ISSUE TITLE
Dealing with undefined facts

### ISSUE THREAD

**Issue by MattCopenhaver** [CacheControl/json-rules-engine#111]
Hi @CacheControl, and thank you for creating/maintaining this library.

I'm planning to use this library to run rules against a fairly large set of input data, where some of the inputs may or may not be defined.  In many cases, if the input data (facts) are not defined, I'd like to fire an event.  So, I set the engine config to `allowUndefinedFacts: true`.

I tried writing a custom operator to check for `undefined` or `null` and would have expected an undefined fact to trigger this event.  You can see this in the code I posted below.

However, based on the docs here: https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#options, it seems and `undefined` fact will automatically result in a `falsey` outcome and not trigger the event.

In this issue, I'm looking to understand the reasoning behind the decision to automatically default to `falsey` in the event of an undefined fact.  It was not intuitive to me, but I may not understand the needs of other users.

I understand there are ways around this by manipulating the input `facts`, but I'd prefer not to do that.  Are there other ways around this through rule definition?

Here's my full code below (with the 3 different fact definitions that each behave differently):
```javascript
let Engine = require('json-rules-engine').Engine
let Rule = require('json-rules-engine').Rule

let engine = new Engine(undefined, {
  allowUndefinedFacts: true
})

// Add custom operator
engine.addOperator('isUndefinedOrNull', (factValue) => { // jsonValue is irrelvant here
  return (factValue === undefined || factValue === null);
});

// Rule definition
let rule = new Rule({
  conditions: {
    any: [
      {
        fact: 'someFact',
        operator: 'isUndefinedOrNull',
        value: true // irrelevant input, related to issue #50 
      }
    ]
  },
  event: { 
    type: 'exampleEvent',
    params: {
      message: 'Event triggered!'
    }
  }
})

engine.addRule(rule);

// Fact definition 
// Note: 3 separate examples, code will not run as-is with all 3 present, pick one
let facts = { // event not triggered
}
let facts = { // event triggered - Output: "Event triggered!""
  someFact: null
}
let facts = { // Error: facts must have a value or method
  someFact: undefined
}

engine
  .run(facts)
  .then(events => {
    events.map(event => console.log(event.params.message))
  })
```

**Comment by marcelpanse** [comment]
I have the exact same problem. Our end user builds the rule-set using our condition builder UI and we allow to build a rule like 'parameter is empty'. This rules should be valid when the parameter does not exist. However, this seems currently impossible to achieve.

How to approach this?

**Comment by marcelpanse** [comment]
@MattCopenhaver why close this without commenting on it? It is still a valid request/concern?
