### ISSUE TITLE
Unable to resolve module `events`

### ISSUE THREAD

**Issue by riverlj** [CacheControl/json-rules-engine#113]
when integrate with react-native project, meeting error like this:

![_c7c3b662-5603-4f34-bc70-9cbe3b7dcb10](https://user-images.githubusercontent.com/6400180/52937721-e155fd80-339a-11e9-871a-f1b45f563980.png)

resolved by add events into package.json。 
can you update the package.json file.

**Comment by CacheControl** [comment]
thanks for reporting this @riverlj! A fix is published in **2.3.3**
