### ISSUE TITLE
fact must be calculate by some math expression

### ISSUE THREAD

**Issue by SamWeichangyue** [CacheControl/json-rules-engine#116]
> Hi @nxtreme this is a rather uncommon case, but you can do this by creating a [dynamic fact](https://github.com/CacheControl/json-rules-engine/blob/master/examples/03-dynamic-facts.js#L63) that returns `fact2` + `fact3`

i have a question ,such as my condition like this 
`{
   conditions: {
        all: [
          {
            fact: 'BMIresult',
            operator: 'lessThan',
            value: 18.5
          },
        ]
      }
},`
but the fact is get from api like websocket or any api call that return fact is weight and height like this 
`{
  weight: 70 , //(kg)
  height: 1.6 //(m)
}`
the fact "BMIresult" must be calculate By formula calculation “BMIresult = weight/(height*height)”, how to resolve this question

**Comment by jsdevtom** [comment]
For custom operators see this example: https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#engineaddoperatorstring-operatorname-function-evaluatefuncfactvalue-jsonvalue

**Comment by JonSilver** [comment]
@SamWeichangyue You should probably think about incorporating an expression parsing computation engine into your process, such as [MathJs](https://mathjs.org/), using it to compute the fact value from your expression string before it's passed to JSON Rules Engine.
