### ISSUE TITLE
Can't run in ie11

### ISSUE THREAD

**Issue by benwicker** [CacheControl/json-rules-engine#122]
Issue: I can't run json-rules-engine in ie11. 

Repro: 
1. Create a new Vue CLI 3 project
2. Install json-rules-engine
3. Import the engine on the hello world component
4. Try to run in IE. 

I get the following error in the console:
![error1](https://user-images.githubusercontent.com/32108642/55725762-55487580-59dc-11e9-96f8-dbce7ca6e599.PNG)
![error2](https://user-images.githubusercontent.com/32108642/55725763-55e10c00-59dc-11e9-89a5-b579ddb8683a.PNG)

**Comment by benwicker** [comment]
I've added a repo here https://github.com/benwicker/json-rules-test

**Comment by jsdevtom** [comment]
@benwicker What was the solution?

**Comment by benwicker** [comment]
Sorry for the delayed reply. My issue was that it wasn't being transpiled. I didn't think about it not being a Vue package and therefore needing a bit more attention. I just had to rework my babel configuration to include it in the transpilation process.
