### ISSUE TITLE
Error "any must be an array" even if an array is passed

### ISSUE THREAD

**Issue by thegeorgeous** [CacheControl/json-rules-engine#124]
The condition in [this line](https://github.com/CacheControl/json-rules-engine/blob/master/src/condition.js#L13) evaluates to false under certain conditions even if `Array.isArray(someArray)` evaluates to true  and `Object.prototype.toString.call(someArray)` returns `[Object Array]`.

Could [these edge cases](https://stackoverflow.com/questions/28779255/is-instanceof-array-better-than-isarray-in-javascript) be the problem?

I'm using [supertest](https://github.com/visionmedia/supertest) and [nock](https://github.com/nock/nock) to test a Cloudflare worker.

Using `Array.isArray()` instead of `instanceof` doesn't seem to be causing any problems for tests. https://github.com/thegeorgeous/json-rules-engine/commit/c2da34fc59d94cc4f8e6f54eaca431b079220f12

Happy to provide any more details if necessary.

UPDATE:
The issue seems to be a [jest issue](https://github.com/facebook/jest/issues/2549). Would you consider using `Array.isArray()` instead?

**Comment by CacheControl** [comment]
@thegeorgeous [looks like](https://jsperf.com/instanceof-array-vs-array-isarray/33) Array.isArray is faster anyway. if you submit a PR I'll happily merge it
