### ISSUE TITLE
How to access facts in rule event?

### ISSUE THREAD

**Issue by HirenPatel2791** [CacheControl/json-rules-engine#126]
Is there a way to get a fact value, in the rule event. For example, 
```
engine.addRule({
    conditions: {
        all:[{
            fact: 'name',
            operator: 'equal',
            value: 'John'
        }]
    },
    event: { 
        type: 'result',
        params: {
          message: 'name is' + **engine.facts.getFact('name')**
        }
    }
});
```

**Comment by CacheControl** [comment]
@HirenPatel2791 When an event fires, there will be an `almanac` object provided as the [second argument](https://github.com/CacheControl/json-rules-engine/blob/master/docs/rules.md#events).  You can then use [almanac.factValue](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#almanacfactvaluefact-fact-object-params-string-path---promise).
