### ISSUE TITLE
rust version of this library

### ISSUE THREAD

**Issue by GopherJ** [CacheControl/json-rules-engine#131]
I'm wondering if we have similar things in rust, that will be wonderful! I spent a lot of time searching and still no idea, this library is very important for our alert engine (nodejs), but now I'm thinking of rewriting our things to `rust`, I would like to find a replacement.

Do you have ideas or plan to write a rust version?

**Comment by CacheControl** [comment]
@GopherJ I know of no plans to write a rust version!
