### ISSUE TITLE
Bypass or remove a rule that has already used, so it is not evaluated in run()

### ISSUE THREAD

**Issue by studiobrain** [CacheControl/json-rules-engine#133]
Using the library, I am able to create a set of rules and their success events. Some of the rules in the sequence will have the same fact: `value pairs`:

```
{
  "conditions": {
    "all": [
      {
        "fact": "confirmation",
        "operator": "equal",
        "value": "Yes"
      }
    ]
  },
  "event": {
    "type": "next",
    "params": {
      "message": "here"
    }
  }
}
```

```
{
  "conditions": {
    "all": [
      {
        "fact": "confirmation",
        "operator": "equal",
        "value": "Yes"
      }
    ]
  },
  "event": {
    "type": "next",
    "params": {
      "message": "next please"
    }
  }
}
```
When I run the rules engine:

```
RulesEngine.run(factChecker).then(events => {events.map(event => {
    // success is always the first truthy event or:
    // "event": {
    //   "type": "next",
    //   "params": {
    //     "message": "here"
    //   }
    // }
}}
```
After the first event truthy event is handled, I would like to be able to bypass it in the next successful `fact: value` pairing

Ive tried removing the rule after applying by setting a uid when creating the rule, but it doesnt seem to work as expected:

```
let appliedRule = RulesEngine.rules.find(
  rule => rule.event.params.id === params.id
);
RulesEngine.removeRule(appliedRule);
```
Is there a better or proper way to mark as applied or flag as move on to the next truthy?

**As always any and all direction is greatly appreciated, so thanks in advance!**

**Comment by omniteq** [comment]
@studiobrain did you manage to solve this somehow? My best idea is to store the information about a successful evaluation of a rule in a database (possibly with onSuccess method). I think you shouldn't remove the rule cause there might be more facts to evaluate later on.

**Comment by CacheControl** [comment]
The desire to remove rules as the engine is running is a good request - something we should support and has been filed in #156. In the meantime, I think the only option would be to track the state of which rules have completed in a variable that lies outsides the engine context, and check it upon each `on('success')` event. Closing as a duplicate for now, but hope to have this feature added soon.
