### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by tettusud** [CacheControl/json-rules-engine#138]
Hi
 I am using the package in browser based project (angular 7), in the later versions its throwing error process is not defined. Its because of debug.js .
However in the older version 2.3.0, it works fine.
Can you check if process exists in debug.js? before applying, so that it won't break ?
Like below

```
if (process && process.env.DEBUG && process.env.DEBUG.match(/json-rules-engine/)) {
    console.log(message)
  }
```

**Comment by CacheControl** [comment]
Thanks for reporting this @tettusud . A fix has been published in **3.0.2**
