### ISSUE TITLE
synchronous run function?  

### ISSUE THREAD

**Issue by MichaelConwayMCG** [CacheControl/json-rules-engine#14]
Can you please add a synchronous run function?  I am not making any I/O calls and everything is in memory in node so your parallel processing provides no benefit and it greatly complicates implementation.  
Or provide me with access your github and I will do it.

**Comment by CacheControl** [comment]
The promise-based api is fairly baked in at this point; a synchronous run would be non-trivial to add.  This doesn't mean it can't be done, simply that we need to keep the effort required proportional to the value it would provide.  Could you describe or perhaps show an example of exactly how this is complicating your implementation?

**Comment by CacheControl** [comment]
Closing this for now.  If you have an opportunity to elaborate this, feel free to reopen; I'd be very interested to hear your thoughts.
