### ISSUE TITLE
Not on entire condition similar to all and any

### ISSUE THREAD

**Issue by karsub231** [CacheControl/json-rules-engine#140]
Not operator on entire condition. An operator similar to how all or any works but unary and returns true when the condition is evaluated to false. Example below:
``
not: {
  any:[{
     fact: 'employee',
     operator: 'equal',
     path: '.company',
     value: 'Microsoft',
    },
    {
     fact: 'employee',
     operator: 'equal',
     path: '.company',
     value: 'Amazon',
    }
  ]
}
``

Agreed that there are other ways to write the rule to support this, but that limits re-use of conditions and reduces using them without writing code for it, Ways are as follows:

1. apply demorgan's law to get to negate the whole condition.
2. add them as dynamic facts and reuse them accordingly.

In my use case, i have a large number of conditions, which are dynamically added to other sets of rules using const objects. The lack of the not cripples this use case. If there is another way of achieving this without adding dynamic facts through code, please let me know.

**Comment by CacheControl** [comment]
@karsub231 In your example, why not simply use an `all` operator and change all of the operators in your conditions to use `notEqual`? Wouldn't that be logically equivalent?

Or are you saying you're in a situation where that's not practical? Can you elaborate?

**Comment by karsub231** [comment]
Yes, I have about 30-40 rules. I would need to apply DeMorgan's law for each of these and store them separately to allow this operation. With not, it is simply use on-demand. I used a simple case. In one scenario the condition is as follows

`
{
    any: [ Condition1(equal operator),
          all:[
                 condtion2(equal),
                 condtion3(equal),
                 condtion4(equal),
                 condtion5(notequal)
             ]
     ]
}
`

Instead of maintaining two rules with opposite operators, a not can do the same thing when invoked as such. Instead of writing rules separately like you mentioned.

**Comment by CacheControl** [comment]
Thanks for elaborating! I think I understand the syntax limitation you're honing in on. Introducing a new `not` operator would constitute a major api change at this point, so we'll need to wait for further evidence to arise before we could consider a change of this magnitude.

One way to work with the existing json-rule-engine design decision would be to write those conditions programmatically - write a method that copies the parameters of each condition, while only changing the operator. I realize this isn't the ideal syntax you're advocating for, but it might be more manageable.

**Comment by karsub231** [comment]
Thanks!

**Comment by sbinlondon** [comment]
Since you seem to be waiting for many people to ask for this feature before deciding to write it, I just want to add that I came here looking for the exact same functionality, so it is something that would be very helpful.

**Comment by sam-w** [comment]
A plus one for this feature too! In fact, I will fork and write the functionality myself, I think. Would you like a pull request when I'm done?

**Comment by sam-w** [comment]
(I understand your reasoning for not having it at this point, btw. And thanks for an excellent and very useful lib!)
