### ISSUE TITLE
Dates comparisons not working

### ISSUE THREAD

**Issue by vasily-blinkov** [CacheControl/json-rules-engine#141]
Please see this runkit notebook to reproduce -- https://runkit.com/vasily-blinkov/5d0253e49efd8200193a463a.

In short, dates comparisons using greater/less operators do not work or I misunderstood something.

**Reproducing**:

```js
const jsonRulesEngine = require("@unless.com/json-rules-engine");
let engine = new jsonRulesEngine.Engine();
engine.addRule({
    conditions: {
        any: [{
            fact: 'date1',
            operator: 'greaterThan',
            value: new Date(2020, 5, 12, 0, 0, 0, 0).valueOf()
        }]
    },
    event: {
        type: 'With .valueOf()'
    }
});
engine.addRule({
    conditions: {
        any: [{
            fact: 'date2',
            operator: 'greaterThan',
            value: new Date(2020, 5, 12, 0, 0, 0, 0)
        }]
    },
    event: {
        type: 'Without .valueOf()'
    }
});
engine
    .run({
        date1: new Date(2020, 5, 13, 0, 0, 0, 0).valueOf(),
        date2: new Date(2020, 5, 13, 0, 0, 0, 0)
    })
    .then(events => events.forEach(e => console.log(e.type)))
```

**Expected** console output is

```
With .valueOf()
Without .valueOf()
```

But **actual** is only limited to

```
With .valueOf()
```

The problem: *I didn't find that using of the `.valueOf()` hack is too good*.
Fix me if I am wrong, but I failed to quick find the answer among the fixed issues.

Thank you.

**Comment by vasily-blinkov** [comment]
Well, I found the next lines finally :)
```js
function numberValidator (factValue) {
  return Number.parseFloat(factValue).toString() !== 'NaN'
}
Operators.push(new Operator('lessThan', (a, b) => a < b, numberValidator))
```
Closing the ticket: I will create a custom operator to compare dates.

**Comment by CacheControl** [comment]
@vasily-blinkov glad you figured it out! and thanks for the runkit link - that's a great tool I wasn't aware of!
