### ISSUE TITLE
Using base operators "+/-" in business rules

### ISSUE THREAD

**Issue by mehdidjs** [CacheControl/json-rules-engine#142]
Hi everyone, 

It's possible to use a simple operator ("sum/diff") in rules ?
For example:
"if (A >= (B+C))"

{           

             fact: 'task',
             path: '.prerequisity_quantity', 
             operator: 'greaterThanInclusive',

             // I want to insert two path and sum them together
             //value: B+C,
             ///value: [{
                            fact: 'parent_task_1',
                            path: '.prerequisity_quantity',                         
                        }+{
                            fact: 'parent_task_2',
                            path: '.prerequisity_quantity',
                           },]       

}
May be like that ???

I spent a lot of time reading docs and try other mean to do it, but can't find how to do it, so thanks advance

**Comment by CacheControl** [comment]
@mehdidjs should be do-able via [dynamic facts](https://github.com/CacheControl/json-rules-engine/blob/master/examples/03-dynamic-facts.js) in combination with [fact comparison](https://github.com/CacheControl/json-rules-engine/blob/master/examples/08-fact-comparison.js)

You'd have a dynamic fact that returns `B+C` (you can retrieve values of existing facts via `almanac.factValue()`), and then your condition would express something like:

```
{
  {
      fact: 'A',
      operator: 'greaterThanInclusive',
      value: {
        fact: 'addFacts',
        params: {
          arg1: 'A',
          arg2: 'B'
        }
      }
    }
}
```

You'll want to take a close look at those examples I linked. Let me know if you run into anything unexpected
