### ISSUE TITLE
Feature Request - Naming Rules for RuleResult Output

### ISSUE THREAD

**Issue by MattCopenhaver** [CacheControl/json-rules-engine#144]
My application has the need to save the result of every rule.  This includes things like rule logic, input fact values, and the result of each rule - all things that are included out of the box in this library with RuleResult 👍 .

However, I also need to record the name of the rule that fired.  This is a concept that exists only to uniquely identify rules stored in my DB and in our records of results, but is largely irrelevant to the execution engine.

I was wondering if this would be a feature you'd be willing to support:
1. An optional field of `id` or `name` when defining a rule:
```javascript
ruleOptions = {
  id: 'Rule1',
  conditions: {
    all: [
      {
        fact: 'my-fact',
        operator: 'equal',
        value: 'some-value'
      }
    ]
  },
  event: {
    type: 'my-event',
    params: {
      customProperty: 'customValue'
    }
  }
}
```
2. Output this in `RuleResult`:
```javascript
{
  id: 'Rule1'
  result: false,
  conditions: {
    all: [
      {
        fact: 'my-fact',
        operator: 'equal',
        value: 'some-value',
        result: false,
        factResult: 'other-value'
      }
    ]
  },
  event: {
    type: 'my-event',
    params: {
      customProperty: 'customValue'
    }
  },
  priority: 1,
}
```

**Comment by MattCopenhaver** [comment]
I'd also be willing to contribute this change if it's something you are good with, @CacheControl.

**Comment by CacheControl** [comment]
@MattCopenhaver I actually may have run into this same problem back in the initial implementation. At the time I _think_ I was able to avoid adding this because the rule's `event.customProperty` could be used to store a unique identifier. Would that work for you?

**Comment by MattCopenhaver** [comment]
I’m away from my computer today, but will check it out as soon as I can and let you know.  Thanks for the quick response.

**Comment by MattCopenhaver** [comment]
@CacheControl While I could make this work, it's less intuitive and would not really be an accurate representation of the information.  It's not a property of the event, it's of the entire rule.
