### ISSUE TITLE
adding the custom script in the rule?

### ISSUE THREAD

**Issue by helxsz** [CacheControl/json-rules-engine#145]
Instead of manually defining the method to retrieve the facts from api, like what the examples has done 

engine.addFact('account-information', function (params, almanac) {
  console.log('loading account information...')
  return almanac.factValue('accountId')
    .then((accountId) => {
      return apiClient.getAccountInformation(accountId)
    })
})

i hope to retrieve the facts from the scripts I have defined, these scripts can be either mongo scripts or sql scripts, 
for example, the mongodb script can be like 
"db.mycollection.find({"name":"foo"}}); "
or sql script can be like 
" select username, age from user"

running the scripts and getting facts from scripts is simple, but the key problem is how to integrate the script into the rules, and save the script along with the rule in json-rule-engine.

Can anyone gives tips or ideas how to do it?

**Comment by CacheControl** [comment]
@helxsz can you elaborate on why you prefer to not use the dynamic facts feature? Dynamic facts were designed to solve the exact situation you're trying to solve.

**Comment by helxsz** [comment]
dynamic facts feature is hard coded while embedding the script (the script for retrieving the facts) can be modified in runtime without hard coding.

**Comment by CacheControl** [comment]
@helxsz dynamic facts don't need to be hard coded to be 1:1 with the script it invokes. For example, you can use the `params` feature of facts to dynamically invoke whatever backend script you like, which requires only a single dynamic fact to be defined:

```js
{
  fact: 'mongodb-query',
  operator: 'equal',
  value: 5,
  params: {
    'query': 'user-age'
  }
}
```

See the [fact dependency](https://github.com/CacheControl/json-rules-engine/blob/master/examples/04-fact-dependency.js) and [dynamic fact](https://github.com/CacheControl/json-rules-engine/blob/master/examples/03-dynamic-facts.js) examples which are relevant.

I believe this achieves your goal of automatically invoking scripts based on rule definition. Of course, the drawback to this technique is that this tightly couples your rule definitions to your codebase. However based on the description of what you're hoping to achieve, this is isn't a concern in your situation.
