### ISSUE TITLE
Browser debug no longer possible

### ISSUE THREAD

**Issue by karlbernard2** [CacheControl/json-rules-engine#147]
Is it possible that since the dependencies on debug module has been removed, that it's no longer possible to debug when running in the browser?

Doesn't seem to use localStorage.debug anymore.

**Comment by CacheControl** [comment]
@karlbernard2 looks like this was broken recently. I've published **3.0.3-beta2** - can you test with that and confirm if it works? thanks!

**Comment by karlbernard2** [comment]
Yes it works, thanks for the quick fix!

**Comment by CacheControl** [comment]
great, thanks for reporting! this is published as **3.0.3**
