### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'origin' of undefined

### ISSUE THREAD

**Issue by KalleV** [CacheControl/json-rules-engine#149]
I'm seeing the following error when trying to use the rule engine in the Node 12 environment:
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'origin' of undefined
    at Window.get localStorage [as localStorage] (/node_modules/jsdom/lib/jsdom/browser/Window.js:256:26)
    at debug (node_modules/json-rules-engine/dist/debug.js:8:165)
    at /node_modules/json-rules-engine/dist/rule.js:255:31
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at async Promise.all`

**Comment by CacheControl** [comment]
@KalleV I believe this is a problem with your jsdom configuration - it's not providing localStorage as a global.

I have a bit of experience with jsdom, and in this past I've solved this with the following [shim](https://github.com/mnahkies/node-storage-shim):

```js
let StorageShim = require('node-storage-shim');
// may have to do 1 or both of these:
global.localStorage = new StorageShim();
window.localStorage = new StorageShim();
```

Unfortunately that's about all the guidance I can provide, as I'm not an expert in jsdom. If you're convinced this is a problem with json-rules-engine, please provide a runnable repo that reproduces the problem.
