### ISSUE TITLE
Possible to run rules against dynamic values?

### ISSUE THREAD

**Issue by bootylactin** [CacheControl/json-rules-engine#15]
We are looking into using your library for a product hierarchy.  We have the need to run a rule based on a dynamic quantity value, where the quantity of a child product cannot exceed the existing quantity of a parent product.  I'm not seeing anything in your examples where value is dynamic.  Is this possible?

Thanks!

**Comment by CacheControl** [comment]
@bootylactin interesting!  I haven't encountered a use case like this before, and these things can be tough to discuss without a lot of context....however perhaps this option might guide you in the right direction, or at least get the conversation started.  This assumes we're run()'ing the engine for a single product that is known at runtime - let me know if this is not the case:

```js

let quantityRule = {
  conditions: {
    all: [{
      fact: 'exceeds-parent-product-quantity',
      operator: 'equal',
      value: false, // i.e. "cannot be allowed to exceed parent product's quantity"
    }]
  },
  event: { /*...*/ }
}
engine.addRule(quantityRule)

engine.addFact('exceeds-parent-product-quantity', function (params, almanac) {
  return almanac.factValue('quantity').then(quantity => { // returns the current product's quantity
     return almanac.factValue('parentQuantities').then(parentQuantities => { // retrieve parent product definition(s)
        return parentQuantities.every(parentQuantity => parentQuantity > quantity) // test that all parent quantities exceed the current product's
      })
    })
})

engine.run({
   quantity: currentProduct.quantity,  
   parentQuantities: [12,43,99]
})
```
 Alternatively, your runtime facts could simply be a `currentProductId`, and you can use facts to load whatever data you need from the database on-demand, and use `almanac.addRuntimeFact` to retrieve later. Unfortunately I just realized I don't have an example of this, so let me know if this is the case and I can provide one.

Finally, if you have a lot of rules like `exceeds-parents-x-property`, you'd probably want to write a generic version of the fact above that can be used with any property (should be doable with the `params` property of the rule. 

Is this close?  Way off base?

**Comment by bootylactin** [comment]
Spot on man, we took what you wrote and it's working beautifully for us, thanks!
