### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by dcworldwide** [CacheControl/json-rules-engine#150]
I've profiled the bundle size of this lib's dependencies. You can see the results here https://bundlephobia.com/scan-results?packages=clone@2.1.2,events@3.0.0,hash-it@4.0.4,lodash.isobjectlike@4.0.0,selectn@1.1.2

<img width="887" alt="Screen Shot 2019-08-09 at 08 33 01" src="https://user-images.githubusercontent.com/4898751/62742059-73081300-ba80-11e9-88a1-9dac4a202105.png">

For my large application, we unfortunately need to be very conservative about the size of new libraries that we introduce into our web bundle. I'm wondering if there is scope for removing some of the deps, with local implementations?

Best

**Comment by kibertoad** [comment]
None of dependencies listed appear to be significantly large, and all of them are simple enough; are you sure in-line implementation is going to be drastically smaller? `lodash.get` is comparable in size to `selectn`, so my guess is that any decent implementation is going to be comparably large.

**Comment by CacheControl** [comment]
@dcworldwide We've made a concerted effort to keep the bundle size small. in fact, from a [historical standpoint](https://bundlephobia.com/result?p=json-rules-engine@3.1.0), the library has never been smaller. You'll also note that dependencies account for only 40% of the entire bundle - in my experience this is  far better than the average npm.

All that to say, there's no low hanging fruit that I'm aware of. Each dependency serves a critical purpose in the functioning of json-rules-engine, and has been vetted as one of the smaller, high quality packages in its class.

I certainly appreciate the desire the minimize dependencies and keep packages lean; the above is not meant to be dismissive. If you have a concrete recommendation for how bundle size can be reduced, please do feel free to open a new issue around the specific case, and I'll lend it serious consideration.
