### ISSUE TITLE
[Proposal] Typescript support

### ISSUE THREAD

**Issue by dcworldwide** [CacheControl/json-rules-engine#151]
I've found progressively adding typescript to my projects has enabled significant wins, specifically the ability to refactor huge swathes of code quickly with confidence and catching a lot of runtime issues that would normally be found later in a dev cycle. Would you be open to Typescript support for this lib? I think it would make tasks such as transitioning to jsonpath much simpler.

**Comment by CacheControl** [comment]
@dcworldwide yes, I am open to typescript support and have been waiting for someone to contribute a `index.d.ts` file that exposes the interfaces. A previous TS effort was made involving a full conversion of the library to typescript, which you can find [here](https://github.com/jsdevtom/truegin). To be clear, I'm not interesting in changing the underlying language to Typescript, however definitely open to exporting types.

**Comment by dcworldwide** [comment]
Thanks Cache for the feedback. I'm going to fork your lib and play around with it to see if it fits out needs. I like the use of json to declare/persist user definable rules. We do prefer to work with TS and will also prefer a more terse json syntax for perf reasons. I can submit PRs should you wish to consider these changes.

**Comment by patwritescode** [comment]
@CacheControl @dcworldwide hey folks. One of our engineers, @scottdj92, added types to the definitely typed repo for this yesterday `@types/json-rules-engine`

**Comment by CacheControl** [comment]
woo! finally! please pass along my gratitude @patwritescode !
