### ISSUE TITLE
Feature Request - Also return almanac after engine.run()

### ISSUE THREAD

**Issue by MattCopenhaver** [CacheControl/json-rules-engine#152]
I have a use case where as I run rules, I sometimes need to add or update runtime facts.  

For a logical example, I have something like this: 

```
Rule 1:
IF fact1 > 1000 (+ more conditions) => set fact1 to fact1 - 100
Rule 2: 
IF fact1 > 1500 (+ other conditions) => set fact1 to fact1 - 100
etc...
```

After the engine run, I need to know what the eventual value of `fact1` has become.  There are ways I can do this currently, but it would be far easier if I had access to the almanac after the engine run.

I could create a PR to accomplish this, but before I do, I have a couple questions:

1. Is this something that should be supported by the engine?  Am I overlooking something?
2. Any recommendations on how to do this without introducing a breaking change?  Or is that not possible?

**Comment by MattCopenhaver** [comment]
I thought of a way to do this in a non-breaking way, by introducing an second options parameter to `engine.run()`.  

`engine.run(runtimeFacts = {})`
becomes
`engine.run(runtimeFacts = {}, options = {})`

If the option `returnAlmanac: true` is passed, instead of returning just the `events`, we can return something like:
```javascript
{
  events: []
  almanac: //the almanac
}
```

@CacheControl thoughts?

**Comment by CacheControl** [comment]
@MattCopenhaver I think this would be a good improvement, and we have prior supporting evidence as this has [come up before](https://github.com/CacheControl/json-rules-engine/issues/81). I'm actually OK with the breaking change in the interest of a more elegant interface - it's definitely one that may impact more than a few people, but in the long term its for the best.

In terms of the interface, I like the one you came up with:
```
{
  events: [],
  almanac: //the almanac
}
```
I think we should have `run()` return this data structure every time, and we'll just document the breaking change in the changelog. Thoughts? The most annoying part of this approach may be fixing all the [examples](https://github.com/CacheControl/json-rules-engine/tree/master/examples) 😄

**Comment by MattCopenhaver** [comment]
That works for me!  I'll work on a PR tomorrow if time permits.

**Comment by MattCopenhaver** [comment]
@CacheControl I just opened #153.  The examples update was not too bad, as most of the examples did not use the `events` from the engine run 😄.
