### ISSUE TITLE
In and notIn operator don't work

### ISSUE THREAD

**Issue by andrealeo83** [CacheControl/json-rules-engine#157]
In and notIn operator don't work.
You have to invert b.indexOf(a) with a.indexOf(b)
These lines:
Operators.push(new Operator('in', (a, b) => b.indexOf(a) > -1))
Operators.push(new Operator('notIn', (a, b) => b.indexOf(a) === -1))
must be:
Operators.push(new Operator('in', (a, b) => a.indexOf(b) > -1))
Operators.push(new Operator('notIn', (a, b) => a.indexOf(b) === -1))

**Comment by MattCopenhaver** [comment]
Do you mean to be using `contains` and `doesNotContain` instead?

https://github.com/CacheControl/json-rules-engine/blob/1583cd6ff8deaa2028cbad295101aeab907be2a8/src/engine-default-operators.js#L11-L12

**Comment by CacheControl** [comment]
`contains` is to be used when the _fact_ is an array. `in` is to be used when the _value_ is an array. See [docs](https://github.com/CacheControl/json-rules-engine/blob/1583cd6ff8deaa2028cbad295101aeab907be2a8/docs/rules.md#array-operators) for more info.
