### ISSUE TITLE
Cannot iterate over an array returned in the fact value, inside the conditions.

### ISSUE THREAD

**Issue by haziz1983** [CacheControl/json-rules-engine#165]
I want to iterate over an array set in the facts inside the conditions to evaluate specific property. Please advise

**Comment by MattCopenhaver** [comment]
Could you be more specific or give an example?

**Comment by haziz1983** [comment]
I have a factValue called "participants-registration", it is an array contains different registrations for a competition, Here is a sample:

  {
    "id": "a132345-4edfr5tg",
    "competitionId": "a132345",
    "participantId": "4edfr5tg",
    "statusInfo": {
      "comment": "Your registration has been started",
      "status": "accepted",
      "approvedBy": "7YHjuiKL",
      "lastUpdatedDate": 1570719374000
    }
  },
  {
    "id": "a132345-4edf9ijp0",
    "competitionId": "a132345",
    "participantId": "4edf9ijp0",
    "statusInfo": {
      "comment": "Your registration has been started",
      "status": "rejected",
      "approvedBy": "7YHjuiKL",
      "lastUpdatedDate": 1570719374000
    }
  },
  {
    "id": "a132345-0okmjoii",
    "competitionId": "a132345",
    "participantId": "0okmjoii",
    "statusInfo": {
      "comment": "Your registration has been started",
      "status": "invited",
      "approvedBy": "7YHjuiKL",
      "lastUpdatedDate": 1570719374000
    }
  }

In the rule's condition I want to check on the status of all the registrations returned. If one of them have the statusInfo.status == "invited", then and event is fired that the registrations approval is not complete.  So int he condition I want to evaluate every status in the array, Please advise how can I acquire this..

**Comment by MattCopenhaver** [comment]
I don’t believe this is possible just using the base operators.  It seems similar to the ‘contains’ operator, but it’s an array of objects and you only want to compare one property.  

I’d suggest using a custom operator similar to contains but allowing an additional parameter to be passed: the path within the array element.

**Comment by CacheControl** [comment]
Thanks @MattCopenhaver for providing an answer.

This is more supporting evidence for a built in operator for evaluating arrays of objects.

This feature request is discussed in #99 - see that thread for an example of adding a custom operator. Closing as dup.
