### ISSUE TITLE
On Success / On Failure as JSON?

### ISSUE THREAD

**Issue by steinhot** [CacheControl/json-rules-engine#166]
For me, the attraction of a json rules engine is that the rules are pure JSON and don't require any functions to run so the rules can all be database driven.

That is true for hit a rule, trigger an event, but it doesn't seem to be true for hit a rule, set a new fact that could be used as facts in subsequent rules. It seems to me the only way to do this would be to use the OnSuccess and onFailure functions with almanac.addRuntimeFact which means that it is no longer static JSON.

Am I missing something?  Thanks for your help and your work on this much needed tool.

**Comment by CacheControl** [comment]
Hi @steinhot. No, you're not missing anything, this was a deliberate design decision. Although simple cases of setting facts dynamically could probably be expressed elegantly in json, it quickly becomes arduous for advanced cases and would essentially require expressing a programming language in json (for example, imagine how difficult it would be to support and express the [custom operator](https://github.com/CacheControl/json-rules-engine/blob/master/examples/06-custom-operators.js#L32) feature in json - although it could probably be done, it'd quickly have everyone begging to have a programmatic hook 🙂).

json-rules-engine seeks to strike a balance between expressing the structure of the rules in a machine readable data structure (json), while enabling complex use cases to be solved via programming.
