### ISSUE TITLE
Ability to access facts in success or failure event

### ISSUE THREAD

**Issue by kssetty** [CacheControl/json-rules-engine#167]
Is there a way to access facts passed for engine.run() from Success or Failure event listeners? I want to bundle the Facts, event & rule result and send to another component for processing.

**Comment by CacheControl** [comment]
@kssetty success and failure events provide the `almanac` reference as the [second argument](https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#engineaddrulerule-instanceobject-options). you can use this with the [almanac.factValue()](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#almanacfactvaluefact-fact-object-params-string-path---promise) method to retrieve fact values. There is also an `almanac. factMap` property(Map type) to retrieve all currently stored facts
