### ISSUE TITLE
Am I able to define several rules and trigger them individually?

### ISSUE THREAD

**Issue by yuriy-vasilyev** [CacheControl/json-rules-engine#170]
Hey guys,

I've defined several rules, but when I run the engine, it always checks if I'm passing all facts from all rules. Am I able to tell the engine what rule I want to run?
I just don't believe I'm not :(

Please help.

Thanks in advance,
Yuriy

**Comment by CacheControl** [comment]
@yuriy-vasilyev One option would be to create a different engine instance for each set of rules you want to run. The design expects that each rule that added to the engine is intended to be executed upon `run()`.

Another option is to use the [allowUndefinedFacts](https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#constructorarray-rules-object-options) option, which will not enforce that every fact is set
