### ISSUE TITLE
How can I add a parameter to the onSuccess event object and display it in the engine results?

### ISSUE THREAD

**Issue by raulrojasadl** [CacheControl/json-rules-engine#173]
I want to add a value to the event map that is displayed in the engine results object, and I am trying to do it in the onSuccess event of each rule.

```
......
onSuccess: function (event, almanac) {
  return almanac
    .factValue('availableAmount')
    .then(availableAmount => {
      let value = (event.params.transferPercent / 100) * availableAmount;
      //try to add transferAmount
      event.params.transferAmount = value.toString();
    });
}

```

But the results of engine not have the transferAmount value.

```
engine
  .run(currentFacts)
  .then(results => {
     console.log("results:", JSON.stringify(results));
});
```
`results: {"events":[{"type":"object","params":{"transferPercent":"50"}}],"almanac":{"factMap":{},"factResultsCache":{},"allowUndefinedFacts":true}}`

Thanks for your help.

**Comment by CacheControl** [comment]
@raulrojasadl there's probably a few different ways we could solve this, but option would be to use [almanac.addRuntimeFact()](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#almanacaddruntimefactstring-factid-mixed-value) to set your new value, and [almanac.factValue()](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#almanacfactvaluefact-fact-object-params-string-path---promise) to retrieve it when the engine completes (via the almanac object returned by [engine.run()](https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#enginerunobject-facts-object-options---promise--events-events-almanac-almanac).

**Comment by raulrojasadl** [comment]
Hi @CacheControl  thanks for your reply. I want to make a generic rule engine, where any calculation in the output variables can be resolved through rules, and not make a custom engine for some cases. My goal is to make any simple calculation as in the example, and only solve it with the rules.
