### ISSUE TITLE
Path result type is inconsistent

### ISSUE THREAD

**Issue by msk-** [CacheControl/json-rules-engine#175]
Before getting to the point, I'd like to say thanks for
1. developing and maintaining this library, it's a nice piece of work
2. implementing the jsonpath functionality, I previously had a horrible "jsonpath" dynamic fact hack for this functionality- I should have made a PR :(

Down to business

A resolved path will sometimes have an array result, and sometimes a non-array result when the input types are the same. This is caused here:
https://github.com/CacheControl/json-rules-engine/blob/master/src/almanac.js#L115
with
```javascript
wrap: false
```
As documented here: https://www.npmjs.com/package/jsonpath-plus#properties
the wrap option reduces ambiguity about the type of the result in one circumstance (`undefined` vs `[]`) but introduces it in another (array types vs. object types) by using a single option to both unwrap single-element arrays and "recast" undefined as an empty array.

An example of the issue in `jsonpath-plus`:
```javascript
const { JSONPath: jp } = require('jsonpath-plus');
const p = {
    arr: [
        { whatever: 1, prop: 'score' },
    ]
};

const path = '$.arr[?(@.whatever == 1)].prop';
const a = jp({ path, json: p, wrap: true });
const b = jp({ path, json: p, wrap: false });
console.log({ a, b });
// prints: { a: [ 'score' ], b: 'score' }
```

This causes ambiguous behaviour in `json-rules-engine`. Specifically, for two sets of facts, `factsSingle` and `factsMultiple` of the same type, the former will cause an error because `jsonpath-plus` has "unwrapped" the array result:
```javascript
const { Engine } = require('json-rules-engine')

const engine = new Engine()

engine.addRule({
  conditions: {
    all: [{
      fact: 'data',
      path: '$.value',
      operator: 'in',
      value: {
        fact: 'data',
        path: '$.arr[?(@.num == 1)]'
      }
    }]
  },
  event: {
    type: 'hello',
    params: {
      message: 'Hi there'
    }
  }
})

const factsSingle = {
  value: 'hello',
  data: {
    arr: [{
      num: 1,
      str: 'hello'
    }]
  }
}

const factsMultiple = {
  value: 'hello',
  data: {
    arr: [{
      num: 1,
      str: 'hello'
    },{
      num: 1,
      str: 'hello'
    }]
  }
}

engine
  .run(factsSingle)
  .then(results => {
    results.events.map(event => console.log(event.params.message))
  })
  .catch(err => {
    console.log(err);
  })

engine
  .run(factsMultiple)
  .then(results => {
    results.events.map(event => console.log(event.params.message))
  })
```

Note the functionality of the `jsonpath` library appears to as what `json-rules-engine` expects (sorry if this is a nuisance to hear, I read the jsonpath issue, I'm aware you went through a selection process!):
```javascript
const jp = require('jsonpath');
const { JSONPath: jpp } = require('jsonpath-plus');

const json = {
    arr: [
        { whatever: 1, prop: 'score' },
    ]
};

const path = '$.arr[?(@.whatever == 1)].prop';
const a = jpp({ path, json, wrap: true });
const b = jpp({ path, json, wrap: false });
const e = jpp({ path: '$.make.something.up', json, wrap: true })
const f =  jpp({ path: '$.make.something.up', json, wrap: false })
console.log({ a, b, e, f });

const c = jp.query(json, path);
const d = jp.query(json, '$.make.something.up');
console.log({ c, d });
```

I have a couple of suggestions to resolve this:
1. raise an issue with `jsonpath-plus`. Perhaps in the interim use `jsonpath`. (If you'd like to take this route, I can handle raising the issue, if you prefer, let me know).
2. parametrise path resolution, i.e. allow users of `json-rules-engine` to supply a path resolution function
3. use `jsonpath` instead of `jsonpath-plus`

Hopefully that's helpful.

**Comment by CacheControl** [comment]
thanks for the detailed writeup @msk! I must have glazed over that part of the `wrap` documentation as I don't remember it - the inconsistent behavior really throws a wrench in things.

I'll take you up the your offer to raise an issue with `jsonpath-plus`; I'm a bit short on time these days. thanks for bringing this to my attention

**Comment by CacheControl** [comment]
Looks like there's an existing issue on this filed over the summer. I've added a follow up: https://github.com/s3u/JSONPath/issues/98

**Comment by msk-** [comment]
Great, thanks, :crossed_fingers: for a quick resolution. Let me know if there's anything I can do to help.
