### ISSUE TITLE
How to run Project

### ISSUE THREAD

**Issue by priyanshuin1** [CacheControl/json-rules-engine#176]
We have install node model after that we have run command "npm start && ng serve " but application is not run .

Please help me how to run project and which one command is run this project.

**Comment by CacheControl** [comment]
Hi @priyanshuin1 

A good place to look is in the examples:
https://github.com/CacheControl/json-rules-engine/tree/master/examples

**Comment by priyanshuin1** [comment]
ok, we have check all structure but when i have clone that project and after that install npm packages then I want to run thins project through "npm start and ng serve" but both are not working.
So , How to run that project on local system and please suggest me can i apply in back-end side and how ?

We have facing issue please help .

Thanks
Priyanshu

**Comment by CacheControl** [comment]
@priyanshuin1 you would run each example via `node <filename>` for example, `node examples/01-hello-world.js`
