### ISSUE TITLE
Any way to debug runtime facts?

### ISSUE THREAD

**Issue by scottdj92** [CacheControl/json-rules-engine#177]
Hi, i'm following an [example](https://github.com/CacheControl/json-rules-engine/blob/master/examples/07-rule-chaining.js) for my application, and i'd like to know if there's a way to view runtime facts for chaining.

ideally i'd like to have the debug log show that a runtime fact was added.

Right now i'm chaining facts, but a check for a runtime fact threw an UndefinedFactError when running the engine.

**Comment by jsdevtom** [comment]
Follow this section: https://github.com/CacheControl/json-rules-engine#debugging

According to the code (I haven't tried it), the engine will log when a file is added:
https://github.com/CacheControl/json-rules-engine/blob/4be7c28a5c9dcf02518d6d333ab2d4c1d95a6799/src/engine.js#L119

**Comment by CacheControl** [comment]
thanks @scottdj92 and apologies for the much delayed response. This is a good suggestion and I've added debug log that now prints when `almanac.addRuntimeFact()` is called. This is published in **5.0.2**
