### ISSUE TITLE
How can i call the engine recursively and access the results via on success and on failure

### ISSUE THREAD

**Issue by qnxrahul** [CacheControl/json-rules-engine#178]
i want to do something like this
recursvice func(old data , new data)
{
if(olddaata !== newData)
{
engine.run(fact);

engine.on('success', function(event, almanac, ruleResult) {
update data 
});
engine.on('success', function(event, almanac, ruleResult) {
update data
});
}
recursivefunc(oldddata,data);
}

**Comment by CacheControl** [comment]
@qnxrahul this is a bit out of scope of this library, as it sounds like a question about recursive flow control with asynchronous libraries. Let me know if there's a problem related to json-rules-engine specifically that makes this use case difficult.

Based on the example you gave above, I noticed you're not `await`ing the `engine.rule()` call (which returns a promise). If you handle that promise correctly such that the next recursive invocation doesn't occur until the promise is resolved, your recursion should work as expected.
