### ISSUE TITLE
anyway to return a value from custom operator (rather than true/false)?

### ISSUE THREAD

**Issue by adham-suwan** [CacheControl/json-rules-engine#181]

**Comment by CacheControl** [comment]
no - this is by design. operators are expect to make a deterministic decision based on the 2 constants they are fed. That said, I'd be interested to know more about your use can and why you might want to design an operator this way.

**Comment by Firetrip** [comment]
Ok so i want to provide a use-case I am having currently:
I have an array of objects as a fact and I want to check for specific combinations within those objects (think trips from and to one location on the same day, each trip is one entry), and i want to count the number of occurrences and use it with a an operator like "greaterThanInclusive". 
that would be really great.

or is this logic that should be represented with an additional fact?
