### ISSUE TITLE
Is it json-rules-engine suitable to run in a serverless environment?

### ISSUE THREAD

**Issue by jorchg** [CacheControl/json-rules-engine#182]
Hello!

We are planning on using `json-rules-engine` as it has all features we need and seems like a good well-crafted package 👍🏻

My main doubt is about using it in a serverless environment, for example in a AWS lambda function. So my thoughts on this are:
- We will have to store our rules in a database
- We will have to load the engine everytime the lambda function is invoked with the rules from the database
- Then facts will be evaluated through an API endpoint executing this lambda function that should respond with events triggered.

Will it be performant enough? We are not hitting scenarios with a low-latency constraint for the moment. Does it fit a serverless deployment like this?

We plan it to have maybe ~400/500 req/min hitting the rule engine. The only part I'm actually not confident with is about feeding the engine everytime with the rules from the database - maybe a couple of hundreds of rules-.

Thank you very much for your help! 👏🏻

**Comment by CacheControl** [comment]
@jorchg I can't speak to the overhead of loading rules from the database, or how many rules we're talking about and the types of conditions you plan to run, but from json-rules-engine's perspective, I would say this sounds like a fairly typical use case. Many users of this library are running their rule engine behind an api of some sort, and we haven't had any recent complaints about performance. Under the hood `json-rules-engine` is just vanilla javascript; I see no reason why it wouldn't perform just fine in a lambda. 

Would definitely be interested in hearing your results!
