### ISSUE TITLE
Dynamic Rule Results

### ISSUE THREAD

**Issue by waglik** [CacheControl/json-rules-engine#183]
Hi

Is it possible to construct dynamic rule result. For example could 

```
event: { 
    type: 'honor-roll',
    params: {
      message: 'Student made the athletics honor-roll'
    }
  }
```
message parameter be constructed in the runtime?

**Comment by CacheControl** [comment]
@waglik Could you tell me more about your use case? Generally I'd recommend adding runtime properties in the [on("success")](https://github.com/CacheControl/json-rules-engine/blob/master/docs/rules.md#ruleonsuccess-functionobject-event-almanac-almanac-ruleresult-ruleresult) event handler, but it's hard to know whether that will work for you without knowing more.

**Comment by waglik** [comment]
@CacheControl Thanks for answering. I am trying to generate list of roles based on user membership in projects. So if user belong to project X I would generate a role MEMBER_PROJECT_X.  I have a list of projects as property of a user. I tried to play with on("success") but I can not overwrite or add anything to the event. Can I?

**Comment by CacheControl** [comment]
@waglik so if a rule evaluates truthy, you want a success event to fire with the project associated with that rule? If this is the case, it sounds like you want to generate a rule per project, programmatically. Then your `params` value for each rule event could contain the project identifier. Would that work?

**Comment by waglik** [comment]
@CacheControl Something like that. So For example, let's assume I have object

`employee = {projects : [x,y,z]} `

I would need to get an event with list of roles `[MEMBER_PROJECT_X, MEMBER_PROJECT_Y, MEMBER_PROJECT_Z]`

but not sure how I can do that. I can check projects property with custom operator, but not sure how I can add dynamic values to `params`

**Comment by MattCopenhaver** [comment]
@waglik I think what you're describing is more of a Dynamic Event rather than a Dynamic Rule Result. 
 
Accessing the `almanac` or `factResult` within `onSuccess` should do the trick.  Your `onSuccess` function will have to contain the logic of how to build the dynamic events/results. 

**onSuccess:** https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#engineonsuccess-functionobject-event-almanac-almanac-ruleresult-ruleresult
**Usage of Alamanc within an `onSuccess`:** https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#retrieve-fact-values-when-handling-events
**Rule Result (contains factResult):** https://github.com/CacheControl/json-rules-engine/blob/master/docs/rules.md#rule-results

**Comment by chandima** [comment]
Can an event be decorated **onSuccess** like below without the added parameters getting permanently added to the rule? 
```
engine.on('success', function(event, almanac, ruleResult) {
  event.params.newProp1 = "decoration 1";
  event.params.newProp2 = "decoration 2";
})
```
However, this results in permanently adding these new parameters to the event section of the rule.

I want to persist the engine instance and only decorate the event for the current engine run but leave the original rule intact for re-use.

**Comment by CacheControl** [comment]
> Can an event be decorated onSuccess like below without the added parameters getting permanently added to the rule?

Couple options here to avoid event mutation impacting other engine runs:

1) You could have a data structure outside of the engine scope that tracks the state, e.g.:
```js
let newEvent
engine.on('success', function(event, almanac, ruleResult) {
  newEvent = cloneDeep(event)
  newEvent.params.newProp1 = "decoration 1";
})
```

2) if you'd prefer to keep things more internal to the engine itself, you could use [almanac.addRuntimeFact()](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#almanacaddruntimefactstring-factid-mixed-value) to save state and then [retrieve it from the almanac later](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#almanacfactvaluefact-fact-object-params-string-path---promise) after run() completes:

```js
engine.on('success', function(event, almanac, ruleResult) {
  newEvent = cloneDeep(event)
  newEvent.params.newProp1 = "decoration 1";
  almanac.addRuntimeFact('new-event', newEvent)
})
const {almanac} = engine.run();
await almanac.factValue('new-event')
```
