### ISSUE TITLE
implement runSync

### ISSUE THREAD

**Issue by antoniopresto** [CacheControl/json-rules-engine#188]
I'll send a PR

**Comment by CacheControl** [comment]
@antoniopresto can you explain what problem this feature would solve? I'm open to reviewing a PR, but I need more context on what use case this solves and why the promise based interface isn't sufficient.

**Comment by antoniopresto** [comment]
Thanks for your work on this awesome library.

In simple cases where I just need to know if a form field (React) is required or not, the asynchronous api ends up generating unnecessary complexity and renders.

**Comment by CacheControl** [comment]
Hi @antoniopresto. Having given this some thought and audited the code changes that this would require, I've unfortunately decided this feature does not belong in the library. The internal flow control required to support promises is already very complex, and I'm concerned that adding a synchronous version of `run()` would require too much overhead to support in the long run; the most important core of the engine would need to be duplicated, rewritten synchronously and maintained.

Apologies that `json-rules-engine` may not meet your needs as a result of this decision, but I believe this is in the best long term interest of the project.
