### ISSUE TITLE
compare fact dependencies between runs to prevent unnecessary rerun

### ISSUE THREAD

**Issue by antoniopresto** [CacheControl/json-rules-engine#189]
I'm planning to submit a PR

**Comment by CacheControl** [comment]
@antoniopresto I'd like to understand this better - can you explain what you mean by fact dependencies, and what you mean by unnecessary re-runs?. 

Each run of the engine is designed to be completely independent of other runs, and the title of this issue suggests we're storing state between runs. The reason for this design decision is it allows a consumer to instantiate an engine with all the rules they need (e.g. upon app startup, or when rules change), and run that engine instance whenever desired.

**Comment by antoniopresto** [comment]
By design, I need to create one engine per react component.

The configuration of each component depends on the other components, so each receives the general state of all components.

The general state is passed as fact to the engine of each component.

If the engine is able to know which facts inside an object with many other facts it depends on, I greatly reduce the number of processing.

An alternative would be to declare in each component which items of the global state are needed, but in my case it is not possible. 
(sorry for my english)

**Comment by CacheControl** [comment]
> The general state is passed as fact to the engine of each component...If the engine is able to know which facts inside an object with many other facts it depends on

This sounds to me like you're passing in a large data structure containing many facts into the engine, but as a single fact (which from the engine's perspective essentially makes this a fact that's a javascript object). This by itself is fine, but having `json-rules-engine` _know_ that this is a fact-of-facts and how to evaluate it feels like it crosses the boundary of what your application does and this library should know about.

I think the tracking of state of what facts contain other facts belong in your application, not in json-rules-engine itself; this is entirely unique to your situation. Feel free to disagree, but I think your application should know what facts/rules a component needs to function, and pass in whatever is required.
