### ISSUE TITLE
Fact path is returning undefined for an array of objects?

### ISSUE THREAD

**Issue by scottdj92** [CacheControl/json-rules-engine#190]
Hi, I'm running into an issue where i have my fact using json-rules-engine@^4.1.0:

```
{
  items: [
    {
      offer: {
        name: 'test item',
        product: {
          name: 'product name',
          template: { name: 'template name' },
          id: '1'
        },
        id: '1234',
        quantity: 1,
        price: { currencyCode: 'USD', amount: 100 }
      },
      id: '385d4a87-f1b2-4a53-9775-ba036f8f007d'
    }
  ]
}
```

and my rule is:
```
{
  fact: "items",
  operator: "contains",
  path: ".name",
  value: "test item"
}
```

running the engine in debug mode, i can see:
```shell
almanac::constructor initialized runtime fact:items with [object Object]<object>
```

but running the condition with the path returns undefined:
```shell
condition::evaluate extracting object property .name, received: undefined
```

which seems weird to me. if the json-path hooks into the `items` array, i should be able to do something like `[*].name` to fetch the name, but the json path evaluates as undefined. I also tried: `$.items[*].offer.name`, but that was also returning undefined.

Is there some implementation detail that i'm missing in the docs?

**Comment by scottdj92** [comment]
Looks like upgrading to 5.0.2 fixes this issue. Was it a disagreement between using the previous json path parsing library and json-path-plus?

**Comment by CacheControl** [comment]
@scottdj92 the json path feature was just added in 5.0.0 - so you were right to upgrade! changelog is [here](https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md#500--2019-11-29)
