### ISSUE TITLE
How to get failed rules from .run method?

### ISSUE THREAD

**Issue by zig999** [CacheControl/json-rules-engine#192]
As I understood, the `engine.run()` method return all the successfull events. I know that we have a failure event, triggered per rule, where I could hook a callback, but that's not what I'm looking for.
What could be done to make `engine.run()` return booth, success and failed rules, an array of **RuleResults** maybe?

I'm using this, but it does not look good to me. 
```javascript
var failedRules = [];
engine1.on("failure", (event, almanac, ruleResult) => {
   failedRules.push(event);
});
```

**Comment by CacheControl** [comment]
@zig999 if you'd like to submit a PR, you could probably follow the pattern of the [success-events](https://github.com/CacheControl/json-rules-engine/blob/master/src/engine.js#L230) and add this feature fairly easily.

**Comment by adamkl** [comment]
@CacheControl This is a feature I'd like as well. 

I'll try to put together a PR this week.

**Comment by stephanepasquini** [comment]
I'm looking for this feature as well ! 

@adamkl let me know if you need help for implementing this feature, thanks!

**Comment by adamkl** [comment]
Hey, sorry, things have been busier than expected at work so I haven't had any time to take a look at this. 

I can post a gist of my current workaround for getting errors out of the rule engine in case that is helpful to anyone in the mean time: 

https://gist.github.com/adamkl/5d89a100300536582e0091e2e2e861db

It's pretty basic (it doesn't handle nested conditions), but its working for my purposes.

**Comment by CacheControl** [comment]
Both `failureEvents` and `failureResults` are now returned by `engine.run()` in **v6.0.0**. See [changelog](https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md#60--2020-12-22)
