### ISSUE TITLE
Compatibility with older browsers

### ISSUE THREAD

**Issue by cbaakel** [CacheControl/json-rules-engine#193]
I've been looking to make this code compatible with the Google Apps Script environment and have run into a number of issues getting all of the code converted, as none of the Babel presets have proven successful.

In example: https://github.com/kenchan0130/babel-preset-google-apps-script/issues/97
Other GAS Babel presets have not proven successful either.

Is there anyway to get this to work with fewer dependencies?

Expected behavior: json-rules-engine can be converted to GAS compatible JS via babel presets

**Comment by CacheControl** [comment]
@cbaakel I read through that issue and it's not clear to me the problem is or how to fix it. If you're able to diagnose what part of json-rules-engine isn't compatible with GAS, please file a specific issue and an example of how to reproduce.
