### ISSUE TITLE
Need to able to add multiple rules, but filter rules based on name that should by run. Also engine class should expose rules as getter property

### ISSUE THREAD

**Issue by sachin27sharma** [CacheControl/json-rules-engine#194]
Following enhancement is needed due to below use case
use case -
1. Ability to load all the rule in the rule engine. 
2. Now, if json schema is used for each grid column, when column cell goes in edit mode, i need to run the rule for only that column definition passing the fact and dependent fact for that column only.
This requires 2 things -
a. Need to able to add multiple rules, but filter rules based on name that should by run. 
b. If filtering before rule run isn't possible, engine class should expose rules as getter property so user know some rules already exists and also method to clear specific rules and a method to clear all rules ClearAllRules(). That can allow user to add new rule and run that rule only.

Since rule are run async, its picking same rule (with same priority) all the time, unless rules array contain only 1 specific rule or ability to filter which rule to run.

**Comment by CacheControl** [comment]
@sachin27sharma could you have a different engine instance per column in your grid? That way you could add only the rules which apply to the current column.

**Comment by sachin27sharma** [comment]
Thanks. Am trying the do the above change.
