### ISSUE TITLE
Property exists operator

### ISSUE THREAD

**Issue by pasblin** [CacheControl/json-rules-engine#195]
There is the possibility of adding a new operator to check if the object contains a property returning true or false?
For example:

`
Operators.push(new Operator('containsProperty', (obj, prop) => Object.prototype.hasOwnProperty.call(obj, prop)))
`
Regards.

**Comment by CacheControl** [comment]
@pasblin for this we provide custom operators (see [docs](https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#engineaddoperatorstring-operatorname-function-evaluatefuncfactvalue-jsonvalue)). You could do something like:

```js
engine.addOperator('hasProperty', (factValue, jsonValue) => {
  return factValue.hasOwnProperty && factValue.hasOwnProperty(jsonValue)
}))
```
