### ISSUE TITLE
Why do "contain" and "doesNotContain" validate for arrays only?

### ISSUE THREAD

**Issue by itayganor** [CacheControl/json-rules-engine#196]
Hi there,
First of all, I wanted to say I really liked this package. It is super useful and powerful. 
I do have one thing that bothers me, and made me create a custom operator for a thing that is rather simple:

If I want to check if a string contains another string, there's no default operator for that. 
For example, If I want to check if my fact has the word **foo** in its `name` property, I need a custom operator. 

I actually dug into the source code and found out that the `contains` operator only validates for arrays. That is because the last parameter supplied to it, which is `Array.isArray`. 

(src/engine-default-operators.js:11)

The implementation of both `contains` and `doesNotContain` uses `indexOf`, which works for both arrays and strings.

Is there a reason to prevent strings from using `contains`?

Thanks!

**Comment by jsdevtom** [comment]
Hi @itayganor,

I think this comment answers your question pretty accuratey: https://github.com/CacheControl/json-rules-engine/issues/90#issuecomment-414716384

**Comment by itayganor** [comment]
> Hi @itayganor,
> 
> I think this comment answers your question pretty accuratey: [#90 (comment)](https://github.com/CacheControl/json-rules-engine/issues/90#issuecomment-414716384)

Thanks! created #197.
