### ISSUE TITLE
Can we introduce operator 'regex' matches?

### ISSUE THREAD

**Issue by RamjiP** [CacheControl/json-rules-engine#199]
I have an idea to introduce the operator 'matches' which will get regex pattern as an input.

e.g.
`
{
        fact: 'hello',
        operator: 'matches',
        value: /world/g
}
`

or 
`
{
        fact: 'hello',
        operator: 'matches',
        value: 'world'
}
`

**Comment by arpitbatra123** [comment]
Hey, @RamjiP You can define a custom operator for your use-case by using `engine.addOperator`. Documentation for the same is available [here](https://github.com/CacheControl/json-rules-engine/blob/feb652af4fc162759fbcead911e2373b75d35b28/docs/engine.md#engineaddoperatorstring-operatorname-function-evaluatefuncfactvalue-jsonvalue).

**Comment by CacheControl** [comment]
per the suggestion above, please use custom operators for this use case
