### ISSUE TITLE
Problem iterating the engine with a list of rule packages

### ISSUE THREAD

**Issue by raulrojasadl** [CacheControl/json-rules-engine#201]
Hi @CacheControl , I need your help.

I'm trying to iterate the engine.run with packages of rules and a initials facts that takes new facts every time that the engine evaluate new rules. The problem is that the engine take the first facts and evaluate all rules with this facts and avoid the new facts.

It's something like this:

```
currentFacts = set initial facts
rulePackages = [ruleList1, ruleList2....]
rulePackages.forEach(ruleList => {
const engine = new Engine(ruleList, engineOptions);
await engine.run(currentFacts).then(results => {
          if (results.events.length > 0) {
            results.events.forEach(e => {
              Object.keys(e.params).forEach(key => {
                   currentFacts[key] = e.params[key];
        });
});
}
});

})
```

The problem is that `currentFacts[key] = e.params[key];` not works, the facts in the  `results` object of every iteration is the same as initial facts.

Thanks for your help.

**Comment by raulrojasadl** [comment]
Hi @CacheControl, sorry for insisting. Do you have any ideas to address this problem?

Thanks for your help.

**Comment by CacheControl** [comment]
What I see in the sample code provided is an asynchronous operation within a foreach. This will cause N number of `engine.run()` promises to be kicked off on the same tick of the event loop, and the changes to `currentFacts` to not occur until the next tick, after the loop has already completed. I think you need to remove the `forEach` and replace it with a for-each technique that supports serial execution of promises (here's [one resource](https://stackoverflow.com/questions/31413749/node-js-promise-all-and-foreach))
