### ISSUE TITLE
engine.run leading to unhandled promise error

### ISSUE THREAD

**Issue by gone-phishing** [CacheControl/json-rules-engine#204]
Getting below when I am running the engine:
`let results = await engine.run(facts);`
`        _.each(results.events, event => {`
`            triggeredevents.push(event.params.data);`
`        })`

error log:
`(node:22949) Warning: a promise was created in a handler at path/node_modules/json-rules-engine/dist/engine.js:278:21 but was not returned from it, see http://goo.gl/rRqMUw`

`    at Function.Promise.cast (path/node_modules/bluebird/js/release/promise.js:225:13)`

**Comment by CacheControl** [comment]
Thanks, I installed bluebird and was not able to make this warning happen. Can you try installing the version of `json-rules-engine` and seeing if you can still reproduce? I haven't had any reports of unhandled promises, so I suspect this is an invalid warning on the part of Bluebird. That said, I'd still like to make it go away for you!
