### ISSUE TITLE
selectn if not installed throws a warning in console

### ISSUE THREAD

**Issue by dumbape** [CacheControl/json-rules-engine#205]
Even if json-path notation (beginning with $) is used, json-rules-engine throws a warning on the console since we do not have 'selectn'

Desired / Optimal behaviour: If selectn syntax for path isn't used, then no warning should appear.

This happens because ES6 does not allow dynamic imports / requires.  All conditional requires are resolved too.

Would it be possible that we keep selectn till the corresponding syntax for `path` is not supported (currently deprecated) -  that would be probably next major release?

**Comment by dumbape** [comment]
@CacheControl

**Comment by ThanosDi** [comment]
Any news on this? Adding selectn as a dependency removes the warnings but breaks my app in some no-
polyfill situations so we can't add it.

```
(undefined) ./node_modules/json-rules-engine/dist/almanac.js
Module not found: Error: Can't resolve 'selectn' in 'node_modules/json-rules-engine/dist'
 @ ./node_modules/json-rules-engine/dist/almanac.js 172:22-40
 @ ./node_modules/json-rules-engine/dist/engine.js
 @ ./node_modules/json-rules-engine/dist/json-rules-engine.js
 @ ./node_modules/json-rules-engine/dist/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/index.js
```

Are there any alternatives to remove these warnings?

**Comment by CacheControl** [comment]
I was _really_ hoping to maintain backwards compatibility, so folks didn't need to update their rules. Given that the old syntax has been deprecated for about a year now, I think the best thing to do is to simply remove the `selectn` support entirely in the next major version. That should alleviate the warnings and build issues.

**Comment by CacheControl** [comment]
All references to `selectn` have been removed in **v6.0.0**. See [changelog](https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md#60--2020-12-22) for details.
