### ISSUE TITLE
Question: able to see a list of loaded rules in an engine? 

### ISSUE THREAD

**Issue by jackie-chan** [CacheControl/json-rules-engine#206]
Is there a way to get the rules that are loaded into an engine? You have all the other CRUD aspects for rules via the engine but I don't see the ability to retrieve the list of rules?

**Comment by arpitbatra123** [comment]
Hey @jackie-chan, You can see the rules that have been loaded into the engine by running `engineInstance.rules`, Where `engineInstance` in the instance you have initialized using `new Engine(...)`

Ref:
![image](https://user-images.githubusercontent.com/21967563/79830380-dfcefd80-83c2-11ea-85f5-65f8c0428520.png)
