### ISSUE TITLE
selectn seems to be faster than json-path for path parsing

### ISSUE THREAD

**Issue by sam-w** [CacheControl/json-rules-engine#210]
I upgraded from 3.x to 5.x and initially took the easy way out of `npm install selectn`, as suggested, for path parsing. More recently, I got around to looking into using `json-path` instead, and noticed that it takes between 1.2 and 3x as long, depending on the number of evaluations being performed!

Is this expected? Is there any drawback to sticking with `selectn`? Happy to provide exact rules and code if required.

v5.0.3
Node.js 12.9

**Comment by hyusetiawan** [comment]
my gut feeling tells me that json-path is the wrong tool for the job. json path is quite extensive in the slicing and dicing of the object, all the things we would "normally" not need if we just want to access the property

**Comment by CacheControl** [comment]
This issue can be solved via the `pathResolver` feature now available **v6.0.0**. See [changelog](https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md#60--2020-12-22) for details.
