### ISSUE TITLE
Rete Algorithm

### ISSUE THREAD

**Issue by radiantone** [CacheControl/json-rules-engine#213]
Does This engine Implement Rete Algorithm or similar efficient firing of rule order?

**Comment by hyusetiawan** [comment]
most likely not, because of the manual ordering, i could be wrong though.

**Comment by CacheControl** [comment]
This library does not implement Rete. It's scales nicely to a point, however the target use case is hundreds/thousands of rules, not millions. For enterprise grade rules engines requiring high scale, there are other solutions well established in that space.
