### ISSUE TITLE
Rule processing - ON Array of objects

### ISSUE THREAD

**Issue by mariovinay-nutanix** [CacheControl/json-rules-engine#214]
Any help would be appreciated !!

I understand this has been brought up before but I couldn't find the answer I was looking for.

Given input facts to the engine such as -
```JavaScript
const facts = {
  cart: {
    prop1: true,
    prop2: "My Cart",
    prop3: {
      prop4: "North America"
    },
    products: [
      {
        category: 1,
        classification: null
      },
      {
        category: 2,
        classification: null
      },
      {
        category: 1,
        classification: null
      }
    ]
  }
};
```

I want to be able to process each object in the products array and define a separate rule for each category and set the classification field for that category.

Something like -
```JavaScript
let condition1 = {
  all: [
    {
      fact: 'category',
      operator: 'equal',
      value: 1
    }
  ]
};

let condition2 = {
  all: [
    {
      fact: 'category',
      operator: 'equal',
      value: 2
    }
  ]
};

let event1 = {
  type: 'category 1 event'
  // Update classification
};

let event2 = {
  type: 'category 2 event'
  // Update classification
};
```

How do I do this? Do i set the classification field in the event handler for that event? How do I access the object the category belongs to? 

I tried using the below, but it selects all the category values from each object. I want to be able to process each object separately.

```JavaScript
let condition = {
  all: [
    {
      fact: 'cart',
      operator: 'contains',
      value: 1,
      path: '$.products[*].category'
    }
  ]
}
```

I cant add them as runTime facts either since you can have only 1 runtime fact and its value. (No Duplicates)

Any help would be appreciated!!

**Comment by CacheControl** [comment]
It seems like this use case could be solved with a hash table of categoryIds to classificationIds and not need a rules engine, so I'm guessing the actual use case is a lot more complex. Here's some general ideas how general ways to track state and pass values to event handlers:

You can set an [event parameter](https://github.com/CacheControl/json-rules-engine/blob/master/docs/rules.md#constructorobject-optionsstring-json) on each event for the classification id that needs to be associated with the given categoryId. You can also maintain a data structure outside the rules engine to store results. e.g.

```js
let event1 = {
  type: 'category 1 event'
  params: { categoryId: 1, classificationId: 3 } // can store constants in "params", which will be passed to the 'success' event handler
};

let results = {} // results could be a mapping of productId => classification, for example
engine.on('success', (event) => {
    console.log(event);  // { type: 'category 1 event' params: { categoryId: 1, classificationId: 3 }
    results[event.params.categoryId] = event.params.classificationId
})
```

Those are some options, hope it helps. One other thing to keep in mind is some use cases require dynamically setting values on each rule event just prior to execution.
