### ISSUE TITLE
returning rule result with successful rules

### ISSUE THREAD

**Issue by dpickett** [CacheControl/json-rules-engine#216]
is there a possibility of returning the correlating `ruleResult` or providing an option to return it in the almanac?

I would add it here: https://github.com/CacheControl/json-rules-engine/blob/master/src/engine.js#L196

My use case is that I need to traverse the successful ruleResults to perform a relevancy calculation (doing some weighting an evaluation of what rules evaluated to true)

Thanks for this awesome library.

**Comment by finchen** [comment]
I would have a use case for that too. 
It makes it easier to unit test our code too and shutdown the database when all the rules callback are finished.

**Comment by finchen** [comment]
I have created a PR for it: https://github.com/CacheControl/json-rules-engine/pull/228

**Comment by CacheControl** [comment]
Rule results are now returned by engine.run() in **v6.0.0**. See [changelog](https://github.com/CacheControl/json-rules-engine/blob/master/CHANGELOG.md#60--2020-12-22)
