### ISSUE TITLE
Rule result is returning always appending previous results as well 

### ISSUE THREAD

**Issue by ZooZoo-tc** [CacheControl/json-rules-engine#218]
Created rule engine object on app startup....(Only one time engine object is created)
When data received from rest api then executing running engine as follows..

this.ruleEngine.run({ data: data});

this.ruleEngine.on('failure', (event: any, almanac: any, ruleResult: any) => {
if (almanac.factMap.has(ruleResult.name)) {
console.log('failure ruleResult', event, almanac.factMap.keys())
}
});

Failure event is giving first time is generating 1 event
Second time receiving data from api then failure event generating 2 events
Third time receiving data from api then failure event generating 3 events.......

Increasing continuously......  Rule results appending to previous results... 

@CacheControl  Could you suggest how to resolve this ?

**Comment by bnimon** [comment]
Interesting there hasn't been help of this one yet, since it seems like a basic requirement.

**Comment by MattCopenhaver** [comment]
I believe this is the intended behavior.  Unless I'm misunderstanding, you should probably be creating new engine instances if you want them to be independent.

**Comment by CacheControl** [comment]
@ZooZoo-tc I think what may be happening is that you are registering a new `on('failure')` event handler in the api route itself. So after N requests you now have N handlers that each need to receive the failure event. You could fix this by registering the event handler outside the api route, or by creating a new engine instance within each api route as @MattCopenhaver correctly points out.

If you'd like to experiment a bit there is some [test coverage](https://github.com/CacheControl/json-rules-engine/blob/4be7c28a5c9dcf02518d6d333ab2d4c1d95a6799/test/engine-run.test.js#L42) around this behavior as well as at least one [example](https://github.com/CacheControl/json-rules-engine/blob/master/examples/07-rule-chaining.js#L85-L96).
