### ISSUE TITLE
Creating engine object every time

### ISSUE THREAD

**Issue by ZooZoo-tc** [CacheControl/json-rules-engine#219]
I would receive data from rest API every 1 minute. I need to validate data for every api request.

How should handle the request? Should I create the engine object on every api request ? 

Could someone suggest .. how to solve this ?

**Comment by ozanerturk** [comment]
Can you please describe your use case more detailed? What you are trying to achieve by using a rule engine?

**Comment by ZooZoo-tc** [comment]
I have an rest API with following structure: 
{
  "device_id":"12345",
  "temperature":30
} 

Client would be calling above API every one minute. I need to validate temperature let's say temperature is very high (grater than 50)

I have tried with creating rule engine object on application start up, 

But while capturing events I am getting events like following .. 
In first request : Temperature High 
In second request : Temperature High,Temperature High 
In third request : Temperature High,Temperature High,Temperature High

Looks like events are not getting cleared.... it's piling up.. 

ruleEngine.on('success', (event: any, almanac: any, ruleResult: any) => {

})

ruleEngine.on('failure', (event: any, almanac: any, ruleResult: any) => {

})

@ozanerturk  @CacheControl I hope you have got clarity on requirement. Could you suggest better ways of creating rule engine

**Comment by ozanerturk** [comment]
Ok. Im gonna try it.
You have an IoT end node and it calls your backend service at regular intervals and you want to have an alarm mechanism by using rules engine.


I am hoping that you are not initiating a rule engine or load rules in every request.

- Initiate rule engine only once
- Load rules only once also first lines of your codes is a good place.

If you want to change rules dynamically do it by using engines methods like, addRule, removeRule
