### ISSUE TITLE
Error after upgrade to 5.0.4 with Angular 10

### ISSUE THREAD

**Issue by toamitc** [CacheControl/json-rules-engine#233]
Below error started coming after upgrade to latest version. This can go away by setting browser vm as false in package.json but that is not correct way for fixing this. so is there any other solution for this?
ERROR in /Users/achugh/Angular/Framework/common-framework-web/node_modules/jsonpath-plus/dist/index-es.js
Module not found: Error: Can't resolve 'vm' in '/Users/achugh/Angular/Framework/common-framework-web/node_modules/jsonpath-plus/dist'

**Comment by liquid36** [comment]
Hi! I have the same error too. In the meanwhile, @toamitc how is this fix in the package.json? 
I really like this version with JSONPath.

**Comment by toamitc** [comment]
@liquid36 - There are couple of solution that you can go but none of them is best if you ask me:
1. add vm dependency in package.json. This should have been taken care by jsonpath-plus if it is really required
2. add below thing in package.json but if you have large scale application with multiple librarties and applications then you will have to end up adding this in all package.json that i don't like.
 "browser": {
    "vm": false
  }
I believe this needs to be fix by jsonpath-plus correctly and they have a bug opened for this. But above solutions can work for a application in the mean time.

**Comment by CacheControl** [comment]
Issue in jsonpath-plus, for reference: https://github.com/JSONPath-Plus/JSONPath/issues/129

**Comment by papadi** [comment]
@CacheControl I followed your advice and helped the guy there to reproduce the problem and he now confirms that it is solved in v5.0.0.

**Comment by papadi** [comment]
Does it make sense to re-open this issue and upgrade the library to the new version?
