### ISSUE TITLE
Ability to get all matched conditions in the event

### ISSUE THREAD

**Issue by zhaoyi0113** [CacheControl/json-rules-engine#246]
In the `events` of the rule response, the `params` can't be set at runtime. It is better to tell which condition matched.

```
engine
  .run(facts)
  .then(({ events }) => {
    events.map(event => console.log(event.params.message))
  })

```

**Comment by CacheControl** [comment]
@zhaoyi0113 I'm not sure I understand your question, can you clarify please?

**Comment by zhaoyi0113** [comment]
Let's take below code as an example. In the last part, `events.map(event => console.log(event.params.message))`, the value of `params` is hard coded in the rule `event` field. Is there a way for me to add parameter at runtime? I'd like to response which condition match in the output `events`. 

```
engine.addRule({
  conditions: {
    any: [{
      all: [{
        fact: 'gameDuration',
        operator: 'equal',
        value: 40
      }, {
        fact: 'personalFoulCount',
        operator: 'greaterThanInclusive',
        value: 5
      }]
    }, {
      all: [{
        fact: 'gameDuration',
        operator: 'equal',
        value: 48
      }, {
        fact: 'personalFoulCount',
        operator: 'greaterThanInclusive',
        value: 6
      }]
    }]
  },
  event: {  // define the event to fire when the conditions evaluate truthy
    type: 'fouledOut',
    params: {
      message: 'Player has fouled out!'
    }
  }
})

/**
 * Define facts the engine will use to evaluate the conditions above.
 * Facts may also be loaded asynchronously at runtime; see the advanced example below
 */
let facts = {
  personalFoulCount: 6,
  gameDuration: 40
}

// Run the engine to evaluate
engine
  .run(facts)
  .then(({ events }) => {
    events.map(event => console.log(event.params.message))
  })
```

**Comment by CacheControl** [comment]
@zhaoyi0113 for information about the conditions that matched, take a look at some of the [other results](https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#enginerunobject-facts-object-options---promise--events--failureevents--almanac-almanac-results--failureresults-) returned by `engine.run()` - it sounds like `results` or `failureResults` may meet your need.

In terms of storing state during engine run(), the recommended approach to that is [almanac.addRuntimeFact](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#almanacaddruntimefactstring-factid-mixed-value).
