### ISSUE TITLE
Ability to accept undefined fact.

### ISSUE THREAD

**Issue by zhaoyi0113** [CacheControl/json-rules-engine#247]
If I send an event which doesn't include all facts, I will get `{"code":"UNDEFINED_FACT"}` error response. It would be better to accept the `undefined_fact` and evaluate the condition which includes the undefined fact as `false`.

**Comment by CacheControl** [comment]
@zhaoyi0113 you can pass the [allowUndefinedFacts](https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#constructorarray-rules-object-options) option into the engine constructor
