### ISSUE TITLE
perfect work,suggestions

### ISSUE THREAD

**Issue by codeneno** [CacheControl/json-rules-engine#248]
1.compare can use < ,> ,>=,<=
2.how to call it dynamiclly?

**Comment by CacheControl** [comment]
hi, I'd refer you to the [examples](https://github.com/CacheControl/json-rules-engine/tree/master/examples) for different use cases. In particular, the [dynamic facts](https://github.com/CacheControl/json-rules-engine/blob/master/examples/03-dynamic-facts.js) may answer your question on dynamic calls.
