### ISSUE TITLE
Abitlity to give description to an individual rule condition

### ISSUE THREAD

**Issue by dbhat6** [CacheControl/json-rules-engine#250]
I'll be creating an application in which there will be hundreds of rules present within the engine and the entire application is running on an express server.

When I receive a fact through an API call, during its logging, I think it would be better to have a description of which rule condition failed so that logging and debugging would be much easier. Making it look something similar to this 
```
{
          fact: "patient-profile",
          operator: "in",
          value: ["123123123", "987987987"],
          path: "$.patientRx.ndc",
          description: "Dummy NDC match",
}
```

Please let me know if there's already a way to get this done.

Versions:
Node: v14.3.0
JSON Rules Engine: 6.0.0

**Comment by CacheControl** [comment]
Hey @dbhat6 you have a couple options here. The first is you can use the [name property](https://github.com/CacheControl/json-rules-engine/blob/master/docs/rules.md#constructorobject-optionsstring-json) to set your rule description. Another would be to add a `ruleDescription` param to the rule event

**Comment by dbhat6** [comment]
But wouldn't these be set on the entire ruleset and not on a specific condition within the entire rule?

**Comment by dbhat6** [comment]
@CacheControl Making it look something like this overall.
```
{
  "name": "global-rule",
  "priority": 999,
  "conditions": {
    "all": [
      {
        "fact": "patient-profile",
        "operator": "equal",
        "value": "true",
        "path": "$.active",
        "description": "Patient is active"
      },
      {
        "fact": "patient-profile",
        "operator": "equal",
        "value": "true",
        "path": "$.text-msg-active",
        "description": "Patient is enabled for text messaging"
      }
    ]
  },
  "event": {
    "type": "global-event",
    "params": {
      "success": {
        "message": "Customer checks out globally"
      },
      "failure": {
        "message": "Customer doesn't check out globally"
      }
    }
  }
}
```

**Comment by CacheControl** [comment]
Ah, apologies, yes I mis-read your issue. This sounds like this would be handled by https://github.com/CacheControl/json-rules-engine/pull/225 which isn't merged yet (and interestingly, when I try and view it I get a 500 error from github) - essentially it's the ability to add success and failure callbacks at the condition level. This is good supporting evidence for prioritizing that PR - so thank you for sharing your use case.

For the time being, you can try turning on [debugging](https://github.com/CacheControl/json-rules-engine#debugging), though I realize that's not the full solution you're looking for.

**Comment by dbhat6** [comment]
Yup, debugging isn't what I want in this scenario 😄 
That PR gave me a 500 the first time but upon reloading it loads fine for me. Yup, that feature would fit right in for my use case. Looking forward to it, thanks @CacheControl!

**Comment by jsdevtom** [comment]
@dbhat6 You said in your original post
> I think it would be better to have a description of which rule condition failed so that logging and **debugging** would be much easier

What do you mean by "debugging isn't what I want in this scenario" then?

**Comment by dbhat6** [comment]
> For the time being, you can try turning on debugging, though I realize that's not the full solution you're looking for.

@jsdevtom I meant **turning on debugging** isn't what I want, as per the suggestion above. Apologies for the confusion caused.
