### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by trysenga** [CacheControl/json-rules-engine#26]
I've looked through the tree here and don't see a license for this. My legal department is pretty strict and I'd love to use this in my next project.

**Comment by CacheControl** [comment]
@trysenga I'll add a license file tonight.  FYI, it is ISC as documented in [package.json](https://github.com/CacheControl/json-rules-engine/blob/master/package.json#L40)

**Comment by CacheControl** [comment]
@trysenga license added [here](https://github.com/CacheControl/json-rules-engine/blob/master/LICENSE)

good luck with your project!
