### ISSUE TITLE
How deep can I go with nested boolean logic

### ISSUE THREAD

**Issue by jhgeluk** [CacheControl/json-rules-engine#261]
Hello,

I was wondering how deep I can go with the nested boolean logic. For example when I want the following "rule":
`if (game duration is 40 AND foul count is or higher than 5 AND (name is Jonah OR name is Dennis)) OR (game duration is 48 AND fould count is or higher than 6) THEN ...`

How would I go about my json rule code?

Can anyone shed some light on this case?

**Comment by CacheControl** [comment]
@jhgeluk The nested logic is evaluated recursively, so you can go as deep as you want! 

See [this example](https://github.com/CacheControl/json-rules-engine/blob/master/examples/02-nested-boolean-logic.js) for how to structure the nesting.
