### ISSUE TITLE
What if you have a `.` for the key in your map / object?

### ISSUE THREAD

**Issue by ardok** [CacheControl/json-rules-engine#27]
Say
```
{
  'a.b': {
    'c': 2
  }
}
```

`path: 'a.b.c'` won't work?
Can we make it accept a list? `path: ['a.b', 'c']` ?
Or is it already there?

**Comment by CacheControl** [comment]
@ardok This functionality is provided to `json-rules-engine` by a dependency called `selectn`.  They have a section in their (README)[https://github.com/wilmoore/selectn.js#support-for-keys-containing-] that covers this case.  Why don't you give that a try.  This is a new use case that I wasn't aware of and haven't tried myself, so let me know if you have any difficulties.
