### ISSUE TITLE
How to save dynamic facts into database

### ISSUE THREAD

**Issue by arsalans** [CacheControl/json-rules-engine#28]
@CacheControl @slmmm
As part of my project, I have to save rules and their dynamic facts in the database. I am able to save and retrieve the rules OK from the database (as they are JSON), wondering how can I do this when my fact is a javascript function like this:

`let factDimensionsCheck = new Fact('fact-dimensions-check', function (params, almanac) {
  return Promise.all([almanac.factValue(params.fact1), almanac.factValue(params.fact2)])
    .then(factValues => {
      let fact1Value = factValues[0];
      let fact2Value = factValues[1];
      let operator = params.operator; 
      return engine.operators.get(operator).evaluate(fact1Value, fact2Value);
    })
});`

**Comment by CacheControl** [comment]
@arsalans Would you mind elaborating on why you need to persist actual code?  The library is designed with the intention that you won't need to do this.  The idea is that you save the rule.toJSON() results into the database, and hydrate a new engine instance when they are later later retrieved.

The fact definitions themselves should remain in code-land, and shouldn't ever need to be persisted.

**Comment by arsalans** [comment]
@CacheControl So I created two micro-services, one creates the rules and facts and saves them into the database, the other one consumes them. With this limitation of not saving methods in Json (not by the engine btw), I may have to merge both of them into one.

**Comment by CacheControl** [comment]
@arsalans If the first microservice is just providing rule CRUD, why does it need to know about the facts?  Why not just have the runner service have the fact definitions?

In case I'm missing something and this is necessary, an alternative to merging the services would be to move the fact definitions into a private npm package and install it into both services.

**Comment by arsalans** [comment]
So the idea is to keep the rules and facts together so that when you have
large number of rules, you know which facts belong to which rule. Easier
maintenance wise.

I am actually liking the idea of moving rules and facts into a separate npm
package and install it into both the services. That might work.

Regards,
Arsalan Siddiqui, BE, MI
Cell : (416) 801-7646
Voip/Fax : (647) 367-4400
http://ca.linkedin.com/in/arsalan
http://www.i-architect.ca

On Feb 16, 2017 8:46 PM, "Cache Hamm" <notifications@github.com> wrote:

@arsalans <https://github.com/arsalans> If the first microservice is just
providing rule CRUD, why does it need to know about the facts? Why not just
have the runner service have the fact definitions?

In case I'm missing something and this is necessary, an alternative to
merging the services would be to move the fact definitions into a private
npm package and install it into both services.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CacheControl/json-rules-engine/issues/28#issuecomment-280524497>,
or mute the thread

**Comment by CacheControl** [comment]
Great, I'll close this for now but feel free to reopen if there are any surprises
