### ISSUE TITLE
Small error in docs

### ISSUE THREAD

**Issue by d-sooter** [CacheControl/json-rules-engine#290]
First of all great product. 

i think there is a small mistake in the coding if i am not mistaken it should be 
product.giftCard=== params.giftCard

https://github.com/CacheControl/json-rules-engine/blob/90272d61ed7bea8b7d4000305511e932490d2e2e/examples/08-fact-comparison.js#L69

**Comment by mrcrumpy** [comment]
I feel like you are mistaken here. The productId in both objects is "giftCard" as a string.

https://github.com/CacheControl/json-rules-engine/blob/90272d61ed7bea8b7d4000305511e932490d2e2e/examples/08-fact-comparison.js#L91

https://github.com/CacheControl/json-rules-engine/blob/90272d61ed7bea8b7d4000305511e932490d2e2e/examples/08-fact-comparison.js#L44
