### ISSUE TITLE
is this project still active

### ISSUE THREAD

**Issue by chalmets** [CacheControl/json-rules-engine#315]
Hi there, 

I am currently evaluating this project to potentially use it in one of my solution.
However, before deciding to use this project instead of another one, I would like to know if this project still active ?
I can see the last release is a bit old and date from 2019.

Sorry for opening an issue for this question, but it's the only way I found to reach out to you.

Thank you

**Comment by joedeveloper** [comment]
@chalmets what did you end up using?

**Comment by MatheusBueno782** [comment]
Hey @chalmets , i'm wandering the same. Have you find a good alternative for this lib?

**Comment by guillaumemeyer** [comment]
@CacheControl ?

**Comment by guillaumemeyer** [comment]
@chalmets interested too to know if you used an alternative...

**Comment by vastamaki** [comment]
Would like to hear an answer to this question. In case this project is dead, I might write something similar using Typescript. Would you guys be interested in contributing if I decide to do so?

**Comment by then3rdman** [comment]
Looking a lot like its not being maintained... I am looking for an alternative...

**Comment by decs** [comment]
@vastamaki I started writing a [more modern version](https://github.com/decs/ruls) of it in Typescript. I’m open for contributors and/or suggestions, if you guys are interested.

**Comment by decs** [comment]
Following up on my previous comment, `ruls` is Typescript-first and it's now ready to use (https://github.com/decs/ruls)

**Comment by chris-pardy** [comment]
It's back! Closing this issue as it's still active.
