### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by mcianc** [CacheControl/json-rules-engine#346]
The new `import { isObject } from 'lodash'` in the `rule-result.js` file generate the following exception for me.

![image](https://github.com/CacheControl/json-rules-engine/assets/97325/0e44e3cb-ef1f-46fb-82b6-775bc8e34164)

using the `lodash.isobjectlike` package you should use
`import { isObject } from 'lodash.isobjectlike'`

I used to have `"json-rules-engine": "^6.1.2"'` in my dependencies, and under the hood it was was automatically updated to the last version after your last 6.4.0 release.
Sorted forcing the package to the initial version `"json-rules-engine": "6.1.2"'`

If I'm not in wrong the `lodash` package is not used in any other source files, most problalby it can be entirely removed from devDependencies, it will not installed when used package will be installed using `npm ci`

**My project details:**
- monorepo using lerna
- server app using nestjs
- `json-rules-engine` imported in a package imported from server as a local dependency

**Comment by chris-pardy** [comment]
@mcianc thanks for the bug report I've pushed a new patch version that should resolve this issue for you.
