### ISSUE TITLE
RuleResult class missing from type declarations

### ISSUE THREAD

**Issue by jeshuamaxey** [CacheControl/json-rules-engine#352]
`RuleResult` has a `toJSON()` method ([source](https://github.com/CacheControl/json-rules-engine/blob/master/src/rule-result.js#L36))

The `RuleResult` interface declaration does not include this ([source](https://github.com/CacheControl/json-rules-engine/blob/master/types/index.d.ts#L127)). Also, there is no class declaration for RuleResult.

The impact of this issue is felt when handling rule results, in my case decomposing them from an EngineResult. I ran into the same problem outlined in https://github.com/CacheControl/json-rules-engine/issues/172 which was "resolved" with the introduction of the `toJSON` method to `RuleResult`s. This resolution doesn't help if you're using typescript, as the compiler has no knowledge of this method.

<img width="963" alt="Screenshot 2023-09-14 at 09 54 49" src="https://github.com/CacheControl/json-rules-engine/assets/2297823/a96df4c0-e88e-4419-913b-72cbe718f6a4">

To make my code work around this, I've had to create a new `RuleResult` type in my code and extend it to include the `toJSON` method, which is a bit yuck.

A good solution would include:

1. add and export a `RuleResult` class declaration which includes the `toJSON()` method
2. add and export a `RuleResultSerializable` type declaration (taking inspiration from the type declaration for [`Rule` class declaration](https://github.com/CacheControl/json-rules-engine/blob/master/types/index.d.ts#L144-L148))

Thanks

**Comment by doblinger-extron** [comment]
Additionally, `result` and `factResult` are missing from `RuleResult`'s `conditions` property.

I believe the `ConditionProperties` interface is the right place to add them, i.e.

```typescript
interface ConditionProperties {
  fact: string;
  operator: string;
  value: { fact: string } | any;
  path?: string;
  priority?: number;
  params?: Record<string, any>;
  name?: string;
  // the following properties are missing
  result: boolean;
  factResult?: any
}
```

In this example, the failures are filtered by the `result` property and this causes compilation errors in TypeScript
https://github.com/CacheControl/json-rules-engine/blob/0de797ccddbe52d2d50e1a4f90db6f830b0ac92a/examples/09-rule-results.js#L48
