### ISSUE TITLE
Async actions on a rule's onSuccess?

### ISSUE THREAD

**Issue by daxiang28** [CacheControl/json-rules-engine#39]
Hi, 
I noticed that promises were not being observed on an onSuccess of rule callback. Seems this way in the code as well. Is there a workaround to this?

Also, what I may be struggling with is the approach to using rules-engines in general and wanting the truthy state of a rule to fire off an action and update the event parameters with the results. Is there a better approach to this?

```
    {
        conditions: {
            all: [
                {
                    fact: 'result',
                    path: '.parameters.email',
                    operator: 'notEqual',
                    value: ''
                }
            ]
        },
        event: { },
        onSuccess: ((event, almanac) => {     
            return almanac.factValue('result')
                .then((result) => {
                    // Do something async. Rule engine completes run before this action completes.
                })
        })
    }
```

Thanks,
Steve

**Comment by CacheControl** [comment]
@daxiang28 Can you expand upon why it's desirable for engine to "pause" and wait for the event to be handled/resolved before continuing execution?  I suspect there may be another way to accomplish what you're after

**Comment by daxiang28** [comment]
Thanks @CacheControl for the quick response. After I read it out loud, 'pausing and waiting for an event' sounds ridiculous. I think my solution is wrapped somewhere in dynamic facts. What I am trying to do has been simplified to these steps so far:

1. Take an incoming fact set and determine what the action is.
2. If an event matches and has a matching async action via a dynamic fact, run it and add that fact
3. Run the engine again
4. Respond with a message for any matched rules that have been updated by a dynamic fact. This is where I am running into issues trying to dynamically populate, hydrate anything in the event to customize the matched event with results from the dynamic fact. 

Some simplified code for what I'm trying to do:
```
const rules = [
        {
            conditions: {
                all: [
                    {
                        fact: 'quote',
                        operator: 'notEqual',
                        value: null
                    }
                ]
            },
            event: {
                type: 'chucked',
                params: {
                    message: 'Hi $user.firstName'
                }
            },
            priority: 5
        }
    ]
    internals._engine = new Engine(rules);
    internals._engine.addFact('request', payload);

    // Placeholder for quote fact key
    // https://github.com/CacheControl/json-rules-engine/issues/29
    internals._engine.addFact('quote', null);

    internals._engine.run()
        .then(events => {
            if (event && event.type === 'harvest') {
                internals._engine.addFact('quote', (params, almanac) => {
                    return almanac.factValue('request')
                        .then((value) => {
                            // Async function here, like look up a user
                            return GetUser('userId')
                        })
                        .catch((e) => {
                            debug(e);
                        });
                });
                return true;
            }
            throw Error();
        })
        .then(() => internals._engine.run())
        .then((events) => {
            // Event should be dymaic
        })
```

**Comment by CacheControl** [comment]
hi @daxiang28, this helps me understand your current approach and what you've tried, but I'm struggling to understand your goal - what it it you're trying to accomplish?

**Comment by daxiang28** [comment]
HI @CacheControl , sorry If i'm not being super clear here. Hopefully simpler, if I could get the event params to update
```
            event: {
                type: 'chucked',
                params: {
                    message: 'Hi $user.firstName'
                }
            },
```
based on a fact value set in between engine runs:
```
                    return almanac.factValue('user')
                        .then((value) => {
                            // Async function here, like look up a user
                            return GetUser('userId')
                        })
                        .catch((e) => {
                            debug(e);
                        });
```

I updated the previous code to reflect some errors that might be confusing.

**Comment by CacheControl** [comment]
@daxiang28 ok, I _think_ I get it now.  Fundamentally it sounds like what we're talking about here is shared state between engine runs.  I'd probably recommend working outside the engine in this case; one of the core design decisions in json-rules-engine is that state **never** carries through between runs.

This should be fairly easy - in your first engine run(), have a variable that stores `user`, which can then be passed to your subsequent run.

e.g.
```js
let userId
engine.addFact('fact-1', (params, almanac) => {
  return somethingThatReturnsUserId
    .then(id => {
        userId = id // store id in a variable scoped with access to both runs()
    })
})

engine.addFact('fact-2', (params, almanac) => {
  return almanac.factValue('userId') // access userId as a fact
    .then(userId => {
         return GetUser(userId)
    })
})

engine
  .run(facts)
  .then(() => {
    // second run; add userId fact
    facts = Object.assign({}, facts, { userId} )
    return engine.run(facts)
  })
  .catch(console.log)
```

This is probably the most idiomatic way to work with the engine for this use case.  Another way to do it would simply to reference the `userId` variable in both dynamic facts and forget passing it as a fact to the second run().

Hope I'm understanding this right and this is helpful.

**Comment by daxiang28** [comment]
@CacheControl yes that's pretty much what I've rejiggered my code to. The one last piece I was hoping to figure out without being so hacky is mutating the rule event params in the success-events array

```
// Using lodash
onSuccess: ((event, almanac) => {
    const updatedParams = { message: 'hi' + user };
    return almanac.factValue('success-events')
        .then(successEvents => _.forEach(successEvents, (successEvent) => {
            if (_.isEqual(successEvent, event)) {
                successEvent.params = updatedParams;
            }
        }));
}
```

**Comment by CacheControl** [comment]
@daxiang28 Ya, it'd be nice if there was a more elegant solution.  If you think of a feature request that would make this easier, please feel free to file it.  For now I'll close this issue as it appears you've found a workaround
