### ISSUE TITLE
Please upgrade dependency jsonpath-plus to 10.1.0 due to critical vulnerability

### ISSUE THREAD

**Issue by Ben-CA** [CacheControl/json-rules-engine#394]
Apparently there is a critical vulnerability with jsonpath-plus < 10.0.7

![image](https://github.com/user-attachments/assets/d9b94666-64e8-457b-9194-27ddb71403b8)

https://www.npmjs.com/package/jsonpath-plus

**Comment by chris-pardy** [comment]
@Ben-CA thanks for raising this.

@CacheControl I think this furthers my desire to get the path handling out of the core engine since this dependency is a pain.

**Comment by buddhamagnet** [comment]
Yes please and thanks for this awesome engine.

**Comment by Ben-CA** [comment]
Thanks for the quick response and update!
