### ISSUE TITLE
Failed compile script 'babel --stage 1 -d dist/ src/'

### ISSUE THREAD

**Issue by slmmm** [CacheControl/json-rules-engine#4]
After installing json-rules-engine from npm, attempted to install the --dev dependencies in order to run tests (i.e. npm test).  Receiving these errord from npm install --dev

**INITIAL ERROR**
`>` babel --stage 1 -d dist/ src/

src/ doesn't exist

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
**npm ERR! json-rules-engine@1.0.1 compile: `babel --stage 1 -d dist/ src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the json-rules-engine@1.0.1 compile script 'babel --stage 1 -d dist/ src/'.**
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the json-rules-engine package,
npm ERR! not with npm itself.

**FOLLOWED BY ERROR**
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN babel-loader@6.2.4 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--only=dev"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
**npm ERR! json-rules-engine@1.0.1 prepublish: `npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the json-rules-engine@1.0.1 prepublish script 'npm run compile'.**

**LOG**
[npm-debug.txt](https://github.com/CacheControl/json-rules-engine/files/314354/npm-debug.txt)

**Comment by CacheControl** [comment]
@slmmm thanks for letting me know, I'll check this out shortly

**Comment by CacheControl** [comment]
@slmmm The npm package is published without the src to cut down on the package size.  If you'd like to run the tests, I'd suggest you git clone the repo: 
```git clone git@github.com:CacheControl/json-rules-engine.git```
```npm install && npm test```

Does that help?

**Comment by CacheControl** [comment]
Awesome!
