### ISSUE TITLE
Incomplete ruleResult.conditions, empty almanac in Node-Red

### ISSUE THREAD

**Issue by JonSilver** [CacheControl/json-rules-engine#42]
Hi there... I tried and loved your json rules engine in node.js, so I tried installing it into the node-red environment using:

```
functionGlobalContext: {
        rulesEngine:require("json-rules-engine")
 }
```

Using a function node, I got the engine processing rules immediately... but strange things happen after the event has finished processing. Although it evaluates all the conditions accurately and fires a success or failure event, ruleResult.conditions received by the callback function is a strangely coded string (as though it's been double-stringified) and incomplete (it carries no evaluation status info, just the original conditions). Additionally, the almanac object is empty.

This is what it looks like:

`conditions: "{"priority":1,"all":["{\"operator\":\"greaterThanInclusive\",\"value\":43,\"fact\":\"brian\"}","{\"operator\":\"greaterThanInclusive\",\"value\":23,\"fact\":\"sally\"}"]}"
`
Obviously this lack of information makes it hard to debug rules. Any ideas?

**Comment by CacheControl** [comment]
@JonSilver Weird!  I'm a bit busy at the moment, but I will look into this when I have a chance.  In the meantime, if you come across any additional information about this issue which may be relevant or are able to provide a snippet that reproduces the issue, please post it.

**Comment by JonSilver** [comment]
@CacheControl Thanks in advance. I've racked my brain and torn my hair out over this one. The code I'm using is an adapted form of 09-rule-results.js so I'm sticking to the letter of how you intended the library to be used. If there was another way of getting at the complete run-log (which conditions were truthy/falsey) for the rule, I'd use it instead, but as far as I can see, there's not.

**Comment by CacheControl** [comment]
@JonSilver that should do it, please re-open if **2.0.1** does not work for you

**Comment by JonSilver** [comment]
Just commenting for closure and completeness - the problem was actually two problems.

Node-Red runs user-supplied code inside a JavaScript VM which upsets json-rules-engine in a few ways. The solution is to use a third-party unsafe code node for rules engine ops.

And the second problem was the serialisation bug, which is now fixed. Thanks!
