### ISSUE TITLE
Can we have new operator forEach?

### ISSUE THREAD

**Issue by shivajivarma** [CacheControl/json-rules-engine#44]
It would be great if we can check facts by looping through inner array.

Sample use case, where student should score greaterThanInclusive of 48 in all subjects.

```js
{
	conditions: {
		any: [{
				all: [{
						fact: 'student.age',
						operator: 'equal',
						value: 40
					}, {
						fact: 'student.name',
						operator: 'greaterThanInclusive',
						value: 'john'
					}
				]
			}, {
				forEach: {
					array: 'student.subjects',
					as: 'subject'
					all: [{
							fact: 'subject.mark',
							operator: 'greaterThanInclusive',
							value: 48
						}, {
							fact: 'subject.name',
							operator: 'equal',
							value: 'maths'
						}
					]
				}

			}
		]
	}
}
```
it's just a thought ...

**Comment by CacheControl** [comment]
Hi @shivajivarma - Apologies for the delayed response, I've been busy in personal life and haven't had much time to attend to opens source lately.

I can certainly see how this might be valuable in many situations!  However, it doesn't quite jive with my vision for this particular library.  _json-rules-engine_ is designed to store rules as a simple, easily parseable data structure without any looping logic or other complex constructs; those are relegated to dynamic facts (i.e. _code_).

So although I can certainly see where you're coming from and appreciate the desire to have this built in, at this time I feel it's not the right fit for this particular library.
