### ISSUE TITLE
Prevent Component redraw, when nothing changes in rules

### ISSUE THREAD

**Issue by mavarazy** [CacheControl/json-rules-engine#46]
Current behavior causes redraw on every key type, even though not schema, nor uiSchema changes, this is costly behavior, which should be prevented

**Comment by CacheControl** [comment]
@mavarazy what do you mean by a `redraw`, `key type`,  `schema` and `uiSchema`?  Can you please expand and be more descriptive?

**Comment by mavarazy** [comment]
@CacheControl Sorry wrong project, working too much
