### ISSUE TITLE
Problem with JSON serialization of rule result

### ISSUE THREAD

**Issue by serban-petrescu** [CacheControl/json-rules-engine#47]
## Summary:
I have an issue when serializing the rule result, namely the conditions inside this result.

## Version
2.0.0

## Example code

```javascript
  let engine = new Engine();
  engine.addRule({
    "priority": 4,
    "event": {
      "type": "something"
    },
    "conditions": {
      "any": [{
        "fact": "data",
        "path": ".age",
        "operator": "lessThan",
        "value": 18
      }]
    }
  });
  engine.on("success", (event: any, almanac: any, result: any) => {
    console.log(JSON.stringify(result))
  })
  engine.run({
    data: {
      age: 16
    }
  });
```

The console will show:

```javascript
{
	"conditions": "{\"priority\":1,\"any\":[\"{\\\"operator\\\":\\\"lessThan\\\",\\\"value\\\":18,\\\"fact\\\":\\\"data\\\",\\\"path\\\":\\\".age\\\"}\"]}",
	"event": {
		"type": "something"
	},
	"priority": 4,
	"result": true
}
```
If I look into the debugger it looks fine:
![image](https://user-images.githubusercontent.com/15961282/27764269-b158eef2-5e95-11e7-948c-ff46d8f08de0.png)

## Cause
I did not really dig into this, but based solely on the debugger contents, I guess you "reused" the `Condition` class for the rule results (at least of the conditions inside it). The custom serialization of this class is most likely causing the issue. IMO, you should make a different "class" for the rule results (condition) object.

**Comment by CacheControl** [comment]
Thanks for the bug report @serban-petrescu 

I have some time available this week and will get a fix put together.

**Comment by JonSilver** [comment]
This is identical to one half of the problem I've been having over in issue #42.

**Comment by CacheControl** [comment]
@serban-petrescu please re-open if **2.0.1** does not fix the issue.
