### ISSUE TITLE
Cannot find module 'babel-core/register'

### ISSUE THREAD

**Issue by slmmm** [CacheControl/json-rules-engine#5]
Attempting to run basic example of Rule Engine in a simple express server app, but unable to use json-rules-engine after npm install.

At first require
`const Engine = require('json-rules-engine');`

Getting error 
> Error: Cannot find module 'babel-core/register'
    at Function.Module._resolveFilename (module.js:440:15)

Looking at stacktrace, requesting babel-core/register from json-rules-engine index.js
![image](https://cloud.githubusercontent.com/assets/19914144/16059844/156a937c-3242-11e6-9202-217923f54c6f.png)

To work-around error, went into json-rules-engine module directory and did an npm install --dev.  But don't believe this is intended resolution.

**Comment by CacheControl** [comment]
@slmmm I believe this is the same root cause as #4 - try a git clone of the repo, and you should be able to run the examples no problem.  I just tried this on a fresh checkout of the repo and it works fine for me.

My apologies for the confusion -- I'll look at adding some documentation on how to run examples.

**Comment by slmmm** [comment]
Actually, what I meant was that I'm just attempting to create simple example of using json-rules-engine. But after using npm install, the attempt to load the module within simple app causes the error "Cannot find module 'babel-core/register'".  Looks like this babel module only installed with devDependencies.  The stacktrace showing reference from dist/index.js.

![jsonrulesengine_installmissingbabel](https://cloud.githubusercontent.com/assets/19914144/16087952/2e3b31c2-32e2-11e6-98d3-7d664a21514f.PNG)

**Comment by CacheControl** [comment]
@slmmm ah, sorry I misunderstood.  I've reproduced the problem, I will work on a solution today.

**Comment by CacheControl** [comment]
@slmmm Thanks for your patience, I've just released 1.0.3 which fixes this issue.  Let me know if you run into any other problems.
