### ISSUE TITLE
Support IE8

### ISSUE THREAD

**Issue by knalbandianbrightgrove** [CacheControl/json-rules-engine#51]
Thank you for the great solution!

Is it possible to support IE8?

The issue is

` getters & setters can not be defined on this javascript engine`

**Comment by CacheControl** [comment]
@knalbandianbrightgrove I have no plans to support IE8, though I'd be open to a PR.

**Comment by knalbandianbrightgrove** [comment]
@CacheControl 

The only thing that breaking IE8 is `lodash.clonedeep` . Is it really need to clone objects in that way? or we can use `JSON.parse(JSON.stringify(object))` instead ?

Regards.
