### ISSUE TITLE
Rete Algorithm

### ISSUE THREAD

**Issue by tetratorus** [CacheControl/json-rules-engine#53]
does this use the rete algorithm?

**Comment by CacheControl** [comment]
@tetratorus No, it does not.  `json-rules-engine` is aimed at solving the 95% of business applications which require a small number of rules (i.e. hundreds/thousands of rules), configured by a simple syntax with an easy to use api.  Applications which would benefit from the performance advantages of Rete are not the target audience, and should look to more robust, enterprise solutions.
