### ISSUE TITLE
Adding custom operators

### ISSUE THREAD

**Issue by hasansaghir** [CacheControl/json-rules-engine#54]
It would be nice to add custom operators to engine that can be used by the rules. For instance I need to check if my fact value as date is with in some range.

**Comment by CacheControl** [comment]
@hasansaghir custom operators is a supported feature, [see docs](https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#engineaddoperatorstring-operatorname-function-evaluatefuncfactvalue-jsonvalue)
