### ISSUE TITLE
fact to evaluate expression

### ISSUE THREAD

**Issue by byronhogoboom** [CacheControl/json-rules-engine#59]
I want to be able to do math in a fact.  Adding to the trickiness the expression variables have different path.  eg: i have object obj that has 2 sub objects a and b and i want to do a fact: obj.a.x * obj.b.y.

Is this possible with custom fact?

**Comment by CacheControl** [comment]
@byronhogoboom You can do any computations you want inside a custom fact.  It is important to remember that the _output_ the fact returns should be consistent based on the input parameters.  So if you are multiplying the values of your inputs together, that should be fine.   If you were doing something that would cause the fact results to vary given the exact same params (like multiplying by a random number, for example), that can be done but is strongly discouraged as it requires you to disable fact caching and incur a performance hit.

I'd suggest doing a quick spike by building off one of the [examples](https://github.com/CacheControl/json-rules-engine/tree/master/examples) to prove out your use case.  If you run into problems just paste the snippet in here and I'll try and help.

**Comment by fergusonIyara** [comment]
Hello, please is there an example pointing to a custom fact?
