### ISSUE TITLE
Almanac not resetting with each run()

### ISSUE THREAD

**Issue by slmmm** [CacheControl/json-rules-engine#6]
I've come across an issue in which I'm using a single Engine instance to run multiple times with each run using different facts and expecting each run to be using a clean Almanac, but it appears the Almanac is reused or caching previous run() facts.

Reading the documentation for the Almanac I expected that facts added in the first run would not exist ("DNE") in subsequent runs.

> Every time engine.run() is invoked, a new almanac is instantiated.

To recreate the issue I'm seeing, I modified the test for verifying independent runs in json-rules-engine (engine-run.test.js), **From documentation, I expected that the 'age' fact would have activated only 1 time across the 6 runs, since the last 3 runs are for fact 'shoesize' and don't include an 'age' fact**.  That being the second proof of the Almanac caching across runs, because this test fails to throw exceptions for Undefined fact 'age' over the last 3 runs.

  describe('SLMMM: independent runs', () => {
    it('treats each run() independently', async () => {
      await Promise.all([0, 0, 0, 30].map((age) => engine.run({age})))
      await Promise.all([7, 9, 5].map((shoesize) => engine.run({shoesize})))
      expect(eventSpy).to.have.been.calledOnce
    })
  })

**Instead, the test fails because there are 4 activations instead of 1.**

 1 failing

  1) Engine: run SLMMM: independent runs treats each run() independently:
     expected spy to have been called exactly once, but it was called 4 times
    spy({ type: "generic" }, [Almanac] { factMap: [Map] {  }, factResultsCache: [Map] {  } }) at emitTwo (events.js:106:13)
    spy({ type: "generic" }, [Almanac] { factMap: [Map] {  }, factResultsCache: [Map] {  } }) at emitTwo (events.js:106:13)
    spy({ type: "generic" }, [Almanac] { factMap: [Map] {  }, factResultsCache: [Map] {  } }) at emitTwo (events.js:106:13)
    spy({ type: "generic" }, [Almanac] { factMap: [Map] {  }, factResultsCache: [Map] {  } }) at emitTwo (events.js:106:13)
  AssertionError: expected spy to have been called exactly once, but it was called 4 times

**Comment by CacheControl** [comment]
@slmmm thanks for reporting this, great catch!  I've release ```1.0.4``` which resolves this issue.

**Comment by zebslc** [comment]
There still seems to be an issue when running parallel tests using ``karma-parallel``.  I have had to set it to run tests individually using [always] as rules events seems to be held in memory when the tests are running.  If I run my tests individually using ``fit`` then the tests run correctly.
