### ISSUE TITLE
Question: How do I stop engine after first matched rule?

### ISSUE THREAD

**Issue by rhushikesh** [CacheControl/json-rules-engine#61]
We have large number of rule set say 150-200, All of them contains priority for execution. 
We only want to retrieve only highest priority rule event, Thats why we want to run the entire rule engine and want to have functionality like findFirst.

Is there a way to achieve this?

**Comment by CacheControl** [comment]
@rhushikesh you should be able to use [engine.stop()](https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#enginestop---engine) within the [engine.on('success')](https://github.com/CacheControl/json-rules-engine/blob/master/docs/engine.md#engineonsuccess-functionobject-event-almanac-almanac-ruleresult-ruleresult) hook
