### ISSUE TITLE
document issue

### ISSUE THREAD

**Issue by sssession** [CacheControl/json-rules-engine#63]
Is there any issue here?

![image](https://user-images.githubusercontent.com/4843262/34925850-ebb3e54c-f9e6-11e7-8389-5c1b2a343c5b.png)

The path property in param, but it is not work.
[https://github.com/CacheControl/json-rules-engine/blob/master/docs/rules.md#condition-helpers-path](url)

And I found the correct method is put it under the root of condition. like example:
[https://github.com/CacheControl/json-rules-engine/blob/master/examples/08-fact-comparison.js#L31](url)

**Comment by CacheControl** [comment]
yep, looks like an error.  Thanks for bringing this to my attention.  I've fixed the docs.
