### ISSUE TITLE
write condition: (fact1.value > (fact2.value + fact3.value))

### ISSUE THREAD

**Issue by nxtreme** [CacheControl/json-rules-engine#66]
Hi! First of all, thank you for this library! But I'm stuck at a very basic step of rules implementation.

let's say we have the following rule that is the equivalent of `if (fact1.value > fact2.value)` (fact comparison as seen in exemples)

```js
let facts = {
	"fact1" : {
		"value": 3
	},
	"fact2" : {
		"value": 2
	},
	"fact3" : {
		"value": 2
	}
}

let rule = {
  conditions: {
    all: [{
      fact: 'fact1',
      path: '.value',
      operator: 'greaterThan',
      value: {
        fact: 'fact2',
        path: '.value',
      }
    }]
  },
  event: { type: 'fact1-greaterthan-fact2' }
}
```
But how to include fact3.value to write the following condition: `(fact.fact1.value > (fact.fact2.value + fact.fact3.value))` ?

If it is supported it would be great to add an exemple to the fact-comparison exemple file.

Thank you for your support

**Comment by CacheControl** [comment]
Hi @nxtreme this is a rather uncommon case, but you can do this by creating a [dynamic fact](https://github.com/CacheControl/json-rules-engine/blob/master/examples/03-dynamic-facts.js#L63) that returns  `fact2` + `fact3`
