### ISSUE TITLE
Dynamic values inside rules

### ISSUE THREAD

**Issue by ganeshcse2991** [CacheControl/json-rules-engine#67]
I am trying to do the following. Please let me know if its possible in any other way.

{
conditions:{
...
..
...
}
event: {
type: sendEmail,
params: {
from_email: $fact.from_email,
subject: "Test subject $fact.subject"
}

I want to place the values from the fact to the rules's event params dynamically.
I am ok with the solution having placeholders too.

Thanks in advance.

**Comment by CacheControl** [comment]
@ganeshcse2991  I would recommend simply storing the fact in a variable outside the engine, and reference it in the `on(success)` event.  Another option is to call `almanac. _getFact(factId)`.  I would not recommend this approach as it's a private method of the library (denoted by the underscore), so it might be removed in future versions...but I mention it in case you don't like or can't do the first option.
