### ISSUE TITLE
Is there a method to remove Rule from an Engine, similar to engine.addRule(rule1) --> engine.removeRule(rule1)

### ISSUE THREAD

**Issue by bharathhs2290** [CacheControl/json-rules-engine#69]

**Comment by CacheControl** [comment]
@bharathhs2290 no, that method does not exist.  You could mutate the internal array that the engine uses to track rules (`engine.rules`), but officially I'd advise against it since that's an internal datastructure and would be exposed to breaking changing in the future.

**Comment by CacheControl** [comment]
This was added in #75 and is available in `json-rules-engine` **2.3.0**
