### ISSUE TITLE
Synchronous run

### ISSUE THREAD

**Issue by ivanetchart** [CacheControl/json-rules-engine#70]
Hi! I'm currently using the engine and it looks really good so far, congratulations!

I have a couple of questions related to the design, is this using Promises for any specific reason ? I did a quick look through the code but I couldn't find any I/O call/nextTick/timer usage, 

I also saw you response on https://github.com/CacheControl/json-rules-engine/issues/14, and be glad to help in case you want to move forward to do a sync approach but adding a Promised interface for `run` method.

Thanks!

**Comment by CacheControl** [comment]
@ivanetchart Can you help me understand the desire for a synchronous run()?  What would that enable?

**Comment by CacheControl** [comment]
Also, to answer your question as to why the promise based interface exists, there are several reasons, primary of which is related to [dynamic facts](https://github.com/CacheControl/json-rules-engine/blob/master/examples/03-dynamic-facts.js).  Although some users of `json-rules-engine` will exclusively use constant facts, other have more complex requirements which necessitate loading data on the fly for both performance and practical reasons.  Having a single promise based interface for all users allows the engine to support _all_ use cases.  

While not having a synchronous run() may be slightly annoying from a syntactic standpoint, having a consistent interface regardless of the way rules and facts are configured is most important.

**Comment by ivanetchart** [comment]
@CacheControl makes totally sense. Thank you so much for the answer, it was totally a question not a need of having a synchronous run. 

About the syntactic part, I don't think it's a problem, but it could mislead assumptions like rules are ran asynchronously, when the only thing that may be async is getting the facts in case they are dynamic, and the rest of it is completely sync. Plus, obviously the Promise handling that may end up having some impact in performance too. 

Again, thanks for taking the time, and anyways I'm open to help in case it's needed.
Have a nice day!
