### ISSUE TITLE
almanac._setFactValue is not updating the fact value

### ISSUE THREAD

**Issue by pavan-syook** [CacheControl/json-rules-engine#71]
i am trying to change the fact value after the rule execution process and i saw your methods from the repo and came by the "_setFactValue" for the almanac object and when trying to update the value of the fact object it does not set the value.

```
let Engine = new RuleEngine.Engine(); 

Engine.addFact('factName', (params, almanac) => {
      return almanac.factValue('FactValueName').then(fact => {
       //Doing some operation to obtain result
      almanac._setFactValue(almanac._getFact('FactValueName'), 'keyToChange', ValueToChange);
     return myValue;
     });
});


Engine.run({factValueName: "value"});
```

**Comment by CacheControl** [comment]
@pavan-syook `_setFactValue` is an internal method and not documented for a reason - it's not intended to be used by consumers of the library.

It looks like you may be looking for a dynamic fact - a fact whose values vary based on the input parameters.  There's an [example](https://github.com/CacheControl/json-rules-engine/blob/master/examples/04-fact-dependency.js#L94) that covers this case.

Alternatively, if you're trying to define a new fact, look at the [rule chaining example](https://github.com/CacheControl/json-rules-engine/blob/master/examples/07-rule-chaining.js#L40) which demonstrates the `addRuntimeFact()` method

**Comment by pavan-syook** [comment]
@CacheControl i saw those methods but i need to update the facts value after a computation and i will try to use the addRunTimeFact() and get back to you on the same thing. But the internal method if made available would be a better enhancement anyways. Thank you for the reply and i will let you know.
