### ISSUE TITLE
Question: What to use for Rule editor UI?

### ISSUE THREAD

**Issue by xumx** [CacheControl/json-rules-engine#72]
Just a question. 

What UI do you guys use to construct the Rules? Nesting rules and having multiple operator types can make the rules rather complex.. Are there any tools that helps in the creation of such rules? 

And good sample to follow?

**Comment by CacheControl** [comment]
@xumx Good question.  I'm not aware of any open source ui projects (in general) for configuring rules engines.  I think most organizations that have used `json-rules-engine` specifically have UI needs/desires bespoke to their business for rule configuration, and therefore it wouldn't make sense to open source.  I know plenty of _enterprise_ rules engines come with a configuration UI, but those are proprietary of course.

It would certainly be nice to see someone take a crack at an OS ui tool, though to your point about complexity it would take some serious investment.
