### ISSUE TITLE
The browser isn't still supported. Is it?

### ISSUE THREAD

**Issue by jsdevtom** [CacheControl/json-rules-engine#77]
I don't see how it can be looking at the source code. Would you mind updating the readme?

**Comment by murraybauer** [comment]
I've been using it in a browser (Angular 2+ app) without problems.

The readme was updated by the owner in this [PR](https://github.com/CacheControl/json-rules-engine/commit/c6e19835bbe96b3aa5ae55103a61ffcf24bf82d2) to explicitly note support.

**Comment by jsdevtom** [comment]
I just checked in the dist folder after installing from npm: `var _events = require('events');`. I am really struggling to understand

**Comment by CacheControl** [comment]
Hey @jsdevtom it's a good question.  If I had to guess, I'd say most everyone using npm packages in the browser these days is using webpack, which lists an  `events` shim under it's [node-libs-browser](https://github.com/webpack/node-libs-browser) dependency.

**Comment by jsdevtom** [comment]
Thank you for the explanation! :tada: I didn't realize webpack did that
