### ISSUE TITLE
Change a fact value from rule event

### ISSUE THREAD

**Issue by flavioseixas** [CacheControl/json-rules-engine#79]
Hi All,
Is it possible to add a new fact from a rule event?
I would like to reproduce the behavior of the code below written in CLIPS, but using json-rules-engine. Any suggestion will be welcome.
[]'s, Flavio.

(defrule determine-runs-properly ""
   (problem-type engine)
   (engine-starting yes)
   (not (repair ?))
   =>
   (assert (runs-properly (yes-or-no-p "Does the engine run normally (yes/no)? "))))

**Comment by CacheControl** [comment]
Hey @flavioseixas , I believe you're looking for [Almanac.addRuntimeFact](https://github.com/CacheControl/json-rules-engine/blob/master/docs/almanac.md#almanacaddruntimefactstring-factid-mixed-value).  There's an example [here](https://github.com/CacheControl/json-rules-engine/blob/81b8de377238a21361ac36bba7d016248ef3ffb6/examples/07-rule-chaining.js).
