### ISSUE TITLE
Fact priority question

### ISSUE THREAD

**Issue by pavan-syook** [CacheControl/json-rules-engine#80]
Now, As per your documentation facts can be prioritized by saying ```{priority: value} ``` this means that the fact with the higher priority is run first.
But the question is If my highest priority fact runs and a falsy is returned , will it carry on to execute the trailing facts or the trailing facts are not Run/Executed at all???

**Comment by CacheControl** [comment]
@pavan-syook It will carry on to execute trailing facts.  What one fact returns does not impact the execution of other facts.
