### ISSUE TITLE
Get almanac after rulesEngine.run function

### ISSUE THREAD

**Issue by voslartomas** [CacheControl/json-rules-engine#81]
Hello, I have a problem, need to get somehow almanac from engine after run, I know about success event which has this parameter, but I need to call some async functions after finished run.

Is there some way?

**Comment by CacheControl** [comment]
Unfortunately there's no way to retrieve the almanac without using the `success` event you mention.  I admit this isn't the most elegant solution, and I'd like to provide a better solution in future versions.  

Something like:
```js
let finalAlmanac
engine.on('success', (event, almanac, ruleResult) => {
  finalAlmanac = almanac
})
await engine.run()

//  now use `finalAlmanac` as necessary
```
