### ISSUE TITLE
Passing fact name to callback in custom operator

### ISSUE THREAD

**Issue by juanto121** [CacheControl/json-rules-engine#82]
Hi there!
I've been looking for ways around an issue when evaluating a custom operator. Here's the thing, the operator I'm using needs the fact name in order to make a request to a db using the name as part of the query and the results are then evaluated with the rule expected value.

As the custom operator only receives the fact value and the expected value, I've been force to duplicate some of the fact params. So the engine input now looks like:

```
var facts = {
		"name":"juan",
		"nameFrequency": { "name": "name", "value": "juan" }
	}
```

Could you suggest a better approach? I could make a pr  that would simplify this by changing the parameters in  [`src/condition.js::evaluate`](https://github.com/CacheControl/json-rules-engine/blob/master/src/condition.js#L103) but maybe there is a way so as not to be disruptive for both my engine clients and/or the project.

Let me know if you would consider including this in the lib

Thanks for any advice.

**Comment by CacheControl** [comment]
@juanto121 apologies for the late response!

It sounds like you may be trying to use the custom operator feature in a situation better suited to dynamic facts.  Custom operators are meant for synchronous comparison of one know value to another, specifically the left hand side of condition equation to the right hand size.

It sounds like you're trying to generate a value (`nameFrequency`) based on an existing fact (`name`).  I'd recommend taking a look at the [dynamic facts](https://github.com/CacheControl/json-rules-engine/blob/master/examples/03-dynamic-facts.js) example, and seeing if you can apply that to your situation.  You may be able to define a `nameFrequency` fact which loads the `name` fact value, and feeds that into the database query to calculate the final value.

If that doesn't work please feel free to elaborate more.
