### ISSUE TITLE
Hi, i faced issue of filter undefined for nested conditions .

### ISSUE THREAD

**Issue by AnupamaPatil** [CacheControl/json-rules-engine#83]
I want to display failed case message on console for nested conditions.My script contains nesting of 'any' and 'all'  operators.

I got error on this line : 
let detail =  ruleResult.conditions.all.filter(condition => !condition.result)
My script is :conditions: {
    any: [
      {
        all: [{
                    fact: 'Designation',
                   operator: 'equal',
                   value: 'NonTeaching'
             },
             {
                    fact: 'leavesApplied',
                    operator: 'lessThanInclusive',
                    value: 12
             }]
      },
      {
        all: [{
                  fact: 'Designation',
                 operator: 'equal',
                 value: 'MedicalPersonnel'
              }, 
             {
                   fact: 'leavesApplied',
                   operator: 'lessThanInclusive',
                   `value:` 16
            }]      
      },
      {
        all: [{
                    fact: 'Designation',
                    operator: 'equal',
                   value: 'PressStaff'
              },
             {
                   fact: 'leavesApplied',
                   operator: 'lessThanInclusive',
                   value: 20
             }]     
      }

**Comment by CacheControl** [comment]
@AnupamaPatil can you please post the error message including the stack trace?

**Comment by AnupamaPatil** [comment]
`TypeError: Cannot read property 'filter' of undefined
    at render (D:\Projects\jsonrulesample\jsonrulesample\Casual
LeaveNonTeachingStaff.js:91:48)
    at Engine.on (D:\Projects\jsonrulesample\jsonrulesample\Cas
ualLeaveNonTeachingStaff.js:114:3)
    at emitThree (events.js:135:13)
    at Engine.emit (events.js:216:7)
    at D:\Projects\jsonrulesample\jsonrulesample\node_modules\j
son-rules-engine\dist\engine.js:277:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by CacheControl** [comment]
@AnupamaPatil The stack trace shows the error is coming from your application code, not json-rules-engine.  The conditions you posted show a root level `any`, which is why `ruleResult.conditions.any.filter` runs properly, but `ruleResult.conditions.all.filter` throws an error; there is no `conditions.all`

I'd recommend throwing some console.log()s on `ruleResult.conditions` so you can view the `ruleResult` data structure.
