### ISSUE TITLE
Question on processing rules with an operator

### ISSUE THREAD

**Issue by hugoduraes** [CacheControl/json-rules-engine#85]
I have a question regarding how the rules engine processes the rules inside an `any` operator. Imagine the following scenario:

Facts:

```js
const example1 = {
  factA: 'A',
  factB: 'B'
}

const example2 = {
  factA: 'A',
  factB: 'SomethingElse'
  factC: 'C'
}
```

Rule:

```json
{
  "conditions": {
    "all": [
      {
        "fact": "factA",
        "operator": "equal",
        "value": "A"
      },
      {
        "any": [
          {
            "fact": "factB",
            "operator": "equal",
            "value": "B"
          },
          {
            "all": [
              {
                "fact": "factB",
                "operator": "notEqual",
                "value": "B"
              },
              {
                "fact": "factC",
                "operator": "equal",
                "value": "C"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

I want both `example1` and `example2` to pass the rule.

`example1` will match the first condition on the `all` operator and the first one on the `any` operator. Rule passes.
`example2` will match the first condition on the `all` operator and the `all` condition on the `any` operator. Rule passes.

My question is... do I need to have an `all` as the second condition for the `any` operator which contains a condition to negate the first condition on the `any` operator? I mean, do the `any` rules get evaluated sequentially or does it evaluate them simultaneously? Could I've written the rule as follows?

```json
{
  "conditions": {
    "all": [
      {
        "fact": "factA",
        "operator": "equal",
        "value": "A"
      },
      {
        "any": [
          {
            "fact": "factB",
            "operator": "equal",
            "value": "B"
          },
          {
            "fact": "factC",
            "operator": "equal",
            "value": "C"
          }
        ]
      }
    ]
  }
}
```

**Comment by CacheControl** [comment]
@hugoduraes The engine will take whatever is fed into it and logically evaluate it; the order in which it evaluates things under the hood should be irrelevant.  Writing the rules in pseudo code shows that the rules are logically identical (that is, I can't think of any input that would pass for rule 1 and fail for rule 2):

Rule 1:
`fA=="A" AND (fB == "B" || (fb != "B" && fC == "C"))`

Rule 2:
`fA=="A" AND (fB == "B" || fC== "C")`

The short answer is yes - you can do the more concise approach of rule 2
