### ISSUE TITLE
Question: How do I create rules that match a property on `any` object in an array?

### ISSUE THREAD

**Issue by tjpeden** [CacheControl/json-rules-engine#86]
Let's say I have a runtime fact as follows:

```javascript
{
  id: 1,
  accounts: [
    { id: 1, type:  'A', amount: 100 },
    { id: 3, type: 'B', amount: 0 },
  ],
}
```

I want to be able to create a rule that succeeds if any account `amount` is say `greaterThan` 0 something of that nature. How do I describe that?

**Comment by CacheControl** [comment]
@tjpeden Apologies for the delayed response.  That situation is tricky.  It probably requires a [dynamic fact](https://github.com/CacheControl/json-rules-engine/blob/master/examples/03-dynamic-facts.js) to do some logic up front.  The fact definition might look something like this:

```js

// create a fact that computes the total balance of a user's accounts
engine.addFact('total-accounts-balance', function (params, almanac) {
  return almanac.factValue('user')
    .then(user => {
      return user.accounts.reduce((acc, currentAccount) => {
           return acc + currentAccount.amount
      }, 0)
    })
})

// And then your rule would simply be:
{
    fact: 'total-accounts-balance',
    operator: 'greaterThan',
    value: 0
}
```

I like to think of dynamic facts as helpers which allow you to manipulate your data into a form that keeps the rules from becoming super complicated.

**Comment by CacheControl** [comment]
@Gby56 The engine cache's facts based on the `fact name` + `params`.  So if the `params` vary with each condition, then the engine will cache each result as separate entries.  This is covered in the [facts docs](https://github.com/CacheControl/json-rules-engine/blob/6b295f1eb92413112f5464e55426038c7fd74b2d/docs/facts.md#constructorstring-id-constantfunctionobject-params-almanac-almanac-object-options---instance)
