### ISSUE TITLE
Getting fact value without promise

### ISSUE THREAD

**Issue by dushyantbangal** [CacheControl/json-rules-engine#93]
I have data in following format:
```
[
    {user:"user1",valueOne:1,valueTwo:2,valueThree:3},
    {user:"user2",valueOne:1,valueTwo:2,valueThree:3},
    {user:"user3",valueOne:1,valueTwo:2,valueThree:3},
]
```

I just need to check each of them for certain conditions, that I have put in rules.

Once a particular rule succeeds, I have to create a payload like the following:
`{user:"user1", eventType:"myevent", valueThree:3}`

However, to get the value of `user` and `valueThree` here, I have to use `almanac.factValue` which returns a promise instead of value.
Is there any way I can directly get the value or the object I supplied to `engine.run`?
I have to collect all the passed and failed results, and then send them to another API. How do I achieve this?

**Comment by CacheControl** [comment]
@dushyantbangal This is intentional - the promise interface of `factValue()` is intended to be used for both synchronous and asynchronous retrieval of fact values.  You can read more about this in #70

**Comment by dushyantbangal** [comment]
My main problem here is I won't know when to push success and fails to the other API, if its all async (unless I do a lot of promise handling). I'm planning to use this in aws lambda function, so time matters too much

**Comment by CacheControl** [comment]
@dushyantbangal Can you post a code snippet that demonstrates the situation?  The asynchronous interface has served everyone's use cases to date, so I suspect if we think through the logic we'll find an approach you'll be happy with.

**Comment by CacheControl** [comment]
> time matters too much

The promise interface shouldn't have a significant impact on your runtime performance.  If it does, please file and issue and I'll dig in.  Runtime performance, particularly around constants (your situation), has been an area of [major focus](https://github.com/CacheControl/json-rules-engine/issues/58).

**Comment by dushyantbangal** [comment]
I think you have used `setImmediate` somewhere maybe to prevent the whole thing from freezing because of rule evaluation and keep the not block the incoming facts, so when I immediately print the `array1` and `array2` after the `forEach`, it prints empty arrays.

I put a `setTimeout` without any milliseconds below the `forEach`, and tried printing `array1` and `array2` inside it, and it worked :)

**Comment by CacheControl** [comment]
@dushyantbangal All the major interfaces into json-rules-engine uses promises, including `Engine.run()`.  So even if there was a synchronous equivalent of `factValue()`, you'd still be running into the asynchronous interface used to run the engine itself.  Am I missing something?

I think if you feel strongly that you must have a synchronous rules engine, you should investigate other projects.  json-rules-engine is a promise-based solution, in order to support the use cases of our asynchronous stakeholders.

**Comment by dushyantbangal** [comment]
@CacheControl you're right, async makes sense. And I didn't really find any other engines that give both failed and passed rules, which I need.

Like I said, 
> I put a setTimeout without any milliseconds below the forEach, and tried printing array1 and array2 inside it, and it worked

this solves my issue. :)

**Comment by CacheControl** [comment]
awesome, glad to hear you figured out an approach!
