### ISSUE TITLE
Is it possible to provide a helper function  to reverse a condtion?

### ISSUE THREAD

**Issue by zhengyhn** [CacheControl/json-rules-engine#94]
Hi,
    I try this engine today. And I found that the event only trigger when the conditions evaluate true. I didn't find any way to set the event trigger when the conditions evaluate false. So I consider to reverse the condition before passing to the engine. Is it possible ? Looking forward for your response. Thank you!

**Comment by CacheControl** [comment]
@zhengyhn this is as designed, and you're correct in your approach of inverting the logic in order to trigger the event
