### ISSUE TITLE
Ability to define failure events

### ISSUE THREAD

**Issue by colps** [CacheControl/json-rules-engine#98]
I have a use case where I want to know about all rules that passed and failed in one place. Currently the events returned by `engine.run()` are only for rules which passed. 
I am aware of the call backs for failure but they are fired per rule. 
Is it possible to define a failure event which will be returned on `engine.run()` in case a rule fails. Essentially, this would mean that `engine.run()` will return a Promise containing events for all rules (passed or failed).

**Comment by CacheControl** [comment]
@colps you'll likely need to hook into those per-rule failure events you mentioned and build and add events an array which can be inspected after run() completes.

**Comment by colps** [comment]
Hi @CacheControl , Thanks for your reply! This was helpful.
